version: "3"

services:
  consul-server-1: &consul-server
    image: consul:latest
    restart: always
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    image: consul:latest
    restart: always
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  api:
    build: ./api
    command: --registry_address=consul-server-bootstrap:8500 --server_address=0.0.0.0:8000
    restart: always
    env_file:
      - .env
    depends_on:
      - user-service
    ports:
      - "8000:8000"

  user-service: &service
    build: ./user
    command: --registry_address=consul-server-bootstrap:8500
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  auth-service:
    <<: *service
    build: ./auth

  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./mysql/data/db:/var/lib/mysql
      - ./mysql/data/conf:/etc/mysql/conf.d
    depends_on:
      - registrator

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
    depends_on:
      - registrator

  weed:
    image: chrislusf/seaweedfs
    restart: always
    ports:
      - "9333:9333"
      - "8080:8080"
    command: server -dir="/data" -volume.publicUrl=${PublicIP}:8080
    volumes:
      - ./fs/data:/data
    depends_on:
      - registrator

  registrator:
    image: gliderlabs/registrator
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://consul-server-bootstrap:8500
    depends_on:
      - consul-server-bootstrap
