// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package fullbottle_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetUserResponse struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Role                 int32    `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	AvatarFid            string   `protobuf:"bytes,6,opt,name=avatarFid,proto3" json:"avatarFid,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	DeleteTime           int64    `protobuf:"varint,10,opt,name=deleteTime,proto3" json:"deleteTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserResponse) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *GetUserResponse) GetAvatarFid() string {
	if m != nil {
		return m.AvatarFid
	}
	return ""
}

func (m *GetUserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUserResponse) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *GetUserResponse) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *GetUserResponse) GetDeleteTime() int64 {
	if m != nil {
		return m.DeleteTime
	}
	return 0
}

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

type ModifyUserRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserRequest) Reset()         { *m = ModifyUserRequest{} }
func (m *ModifyUserRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyUserRequest) ProtoMessage()    {}
func (*ModifyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *ModifyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserRequest.Unmarshal(m, b)
}
func (m *ModifyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserRequest.Marshal(b, m, deterministic)
}
func (m *ModifyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserRequest.Merge(m, src)
}
func (m *ModifyUserRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyUserRequest.Size(m)
}
func (m *ModifyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserRequest proto.InternalMessageInfo

func (m *ModifyUserRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ModifyUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ModifyUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ModifyUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserResponse) Reset()         { *m = ModifyUserResponse{} }
func (m *ModifyUserResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyUserResponse) ProtoMessage()    {}
func (*ModifyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *ModifyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserResponse.Unmarshal(m, b)
}
func (m *ModifyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserResponse.Marshal(b, m, deterministic)
}
func (m *ModifyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserResponse.Merge(m, src)
}
func (m *ModifyUserResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyUserResponse.Size(m)
}
func (m *ModifyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserResponse proto.InternalMessageInfo

type UserLoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{6}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expire               int64    `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{7}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserLoginResponse) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type GetUserAvatarRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserAvatarRequest) Reset()         { *m = GetUserAvatarRequest{} }
func (m *GetUserAvatarRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserAvatarRequest) ProtoMessage()    {}
func (*GetUserAvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{8}
}

func (m *GetUserAvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAvatarRequest.Unmarshal(m, b)
}
func (m *GetUserAvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAvatarRequest.Marshal(b, m, deterministic)
}
func (m *GetUserAvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAvatarRequest.Merge(m, src)
}
func (m *GetUserAvatarRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserAvatarRequest.Size(m)
}
func (m *GetUserAvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAvatarRequest proto.InternalMessageInfo

func (m *GetUserAvatarRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetUserAvatarResponse struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Avatar               []byte   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserAvatarResponse) Reset()         { *m = GetUserAvatarResponse{} }
func (m *GetUserAvatarResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserAvatarResponse) ProtoMessage()    {}
func (*GetUserAvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{9}
}

func (m *GetUserAvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAvatarResponse.Unmarshal(m, b)
}
func (m *GetUserAvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAvatarResponse.Marshal(b, m, deterministic)
}
func (m *GetUserAvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAvatarResponse.Merge(m, src)
}
func (m *GetUserAvatarResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserAvatarResponse.Size(m)
}
func (m *GetUserAvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAvatarResponse proto.InternalMessageInfo

func (m *GetUserAvatarResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *GetUserAvatarResponse) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type UploadUserAvatarRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Avatar               []byte   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadUserAvatarRequest) Reset()         { *m = UploadUserAvatarRequest{} }
func (m *UploadUserAvatarRequest) String() string { return proto.CompactTextString(m) }
func (*UploadUserAvatarRequest) ProtoMessage()    {}
func (*UploadUserAvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{10}
}

func (m *UploadUserAvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadUserAvatarRequest.Unmarshal(m, b)
}
func (m *UploadUserAvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadUserAvatarRequest.Marshal(b, m, deterministic)
}
func (m *UploadUserAvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadUserAvatarRequest.Merge(m, src)
}
func (m *UploadUserAvatarRequest) XXX_Size() int {
	return xxx_messageInfo_UploadUserAvatarRequest.Size(m)
}
func (m *UploadUserAvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadUserAvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadUserAvatarRequest proto.InternalMessageInfo

func (m *UploadUserAvatarRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UploadUserAvatarRequest) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

type UploadUserAvatarResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadUserAvatarResponse) Reset()         { *m = UploadUserAvatarResponse{} }
func (m *UploadUserAvatarResponse) String() string { return proto.CompactTextString(m) }
func (*UploadUserAvatarResponse) ProtoMessage()    {}
func (*UploadUserAvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{11}
}

func (m *UploadUserAvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadUserAvatarResponse.Unmarshal(m, b)
}
func (m *UploadUserAvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadUserAvatarResponse.Marshal(b, m, deterministic)
}
func (m *UploadUserAvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadUserAvatarResponse.Merge(m, src)
}
func (m *UploadUserAvatarResponse) XXX_Size() int {
	return xxx_messageInfo_UploadUserAvatarResponse.Size(m)
}
func (m *UploadUserAvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadUserAvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadUserAvatarResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "fullbottle.srv.user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "fullbottle.srv.user.GetUserResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "fullbottle.srv.user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "fullbottle.srv.user.CreateUserResponse")
	proto.RegisterType((*ModifyUserRequest)(nil), "fullbottle.srv.user.ModifyUserRequest")
	proto.RegisterType((*ModifyUserResponse)(nil), "fullbottle.srv.user.ModifyUserResponse")
	proto.RegisterType((*UserLoginRequest)(nil), "fullbottle.srv.user.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "fullbottle.srv.user.UserLoginResponse")
	proto.RegisterType((*GetUserAvatarRequest)(nil), "fullbottle.srv.user.GetUserAvatarRequest")
	proto.RegisterType((*GetUserAvatarResponse)(nil), "fullbottle.srv.user.GetUserAvatarResponse")
	proto.RegisterType((*UploadUserAvatarRequest)(nil), "fullbottle.srv.user.UploadUserAvatarRequest")
	proto.RegisterType((*UploadUserAvatarResponse)(nil), "fullbottle.srv.user.UploadUserAvatarResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xed, 0x6e, 0xd3, 0x30,
	0x14, 0x5d, 0xd6, 0x0f, 0xd6, 0x5b, 0x3e, 0x5a, 0xd3, 0x41, 0x14, 0x21, 0x54, 0x05, 0x18, 0x05,
	0x41, 0x91, 0xe0, 0x09, 0xa6, 0x21, 0x10, 0x12, 0xfc, 0x20, 0x6c, 0x7f, 0x10, 0x08, 0x79, 0xcd,
	0x2d, 0x44, 0xa4, 0x71, 0x66, 0x3b, 0x85, 0x3d, 0x0b, 0xef, 0xc7, 0x73, 0x20, 0x3b, 0x4e, 0xea,
	0xb6, 0x49, 0x56, 0xf1, 0xa7, 0xca, 0xb9, 0xe7, 0xf8, 0x1e, 0xe7, 0xde, 0x13, 0x15, 0x0e, 0x53,
	0xce, 0x24, 0x7b, 0x91, 0x09, 0xe4, 0xfa, 0x67, 0xaa, 0x31, 0xb9, 0x3d, 0xcf, 0xe2, 0xf8, 0x9c,
	0x49, 0x19, 0xe3, 0x54, 0xf0, 0xe5, 0x54, 0x51, 0xbe, 0x0f, 0x37, 0xdf, 0xa2, 0x3c, 0x13, 0xc8,
	0x03, 0xbc, 0xc8, 0x50, 0x48, 0x32, 0x80, 0x56, 0x16, 0x85, 0xae, 0x33, 0x76, 0x26, 0xad, 0x40,
	0x3d, 0xfa, 0x7f, 0xf6, 0xe1, 0x56, 0x29, 0x12, 0x29, 0x4b, 0x04, 0x6e, 0xab, 0x88, 0x07, 0x07,
	0xaa, 0x63, 0x42, 0x17, 0xe8, 0xee, 0x8f, 0x9d, 0x49, 0x2f, 0x28, 0xb1, 0xe2, 0x52, 0x2a, 0xc4,
	0x2f, 0xc6, 0x43, 0xb7, 0x95, 0x73, 0x05, 0x26, 0x23, 0xe8, 0xe0, 0x82, 0x46, 0xb1, 0xdb, 0xd6,
	0x44, 0x0e, 0x08, 0x81, 0x36, 0x67, 0x31, 0xba, 0x9d, 0xb1, 0x33, 0xe9, 0x04, 0xfa, 0x99, 0xdc,
	0x83, 0x1e, 0x5d, 0x52, 0x49, 0xf9, 0x9b, 0x28, 0x74, 0xbb, 0x5a, 0xbd, 0x2a, 0x90, 0x3b, 0xd0,
	0x15, 0x92, 0xca, 0x4c, 0xb8, 0xd7, 0xf4, 0x19, 0x83, 0xc8, 0x7d, 0x80, 0x19, 0x47, 0x2a, 0xf1,
	0x34, 0x5a, 0xa0, 0x7b, 0xa0, 0x2f, 0x6c, 0x55, 0x14, 0x9f, 0xa5, 0x61, 0xc1, 0xf7, 0x72, 0x7e,
	0x55, 0x51, 0x7c, 0x88, 0x31, 0x1a, 0x1e, 0x72, 0x7e, 0x55, 0xf1, 0x29, 0x0c, 0x4f, 0x74, 0x37,
	0x7b, 0x88, 0xf6, 0x30, 0x9c, 0x86, 0x61, 0xec, 0xd7, 0x0d, 0xa3, 0x65, 0x0d, 0xc3, 0x1f, 0x01,
	0xb1, 0x2d, 0xf2, 0x15, 0xf8, 0x5f, 0x61, 0xf8, 0x81, 0x85, 0xd1, 0xfc, 0xb2, 0x71, 0x7b, 0xff,
	0xbb, 0x17, 0x65, 0x6a, 0xb7, 0x37, 0xa6, 0xaf, 0x61, 0xa0, 0xf0, 0x7b, 0xf6, 0x3d, 0x4a, 0x0a,
	0xcf, 0xf2, 0xd2, 0x8e, 0xbd, 0xc1, 0x86, 0xd7, 0xf4, 0x8f, 0x61, 0x68, 0x75, 0x31, 0x91, 0x1a,
	0x41, 0x47, 0xb2, 0x9f, 0x98, 0x14, 0x6d, 0x34, 0x50, 0x6b, 0xc5, 0xdf, 0x69, 0xc4, 0xf3, 0xcb,
	0xb7, 0x02, 0x83, 0xfc, 0x09, 0x8c, 0x4c, 0x26, 0x8f, 0x75, 0x04, 0xea, 0xe3, 0xfb, 0x11, 0x0e,
	0x37, 0x94, 0xc6, 0x70, 0x0c, 0xfd, 0x19, 0x4b, 0x24, 0x26, 0xf2, 0xf4, 0x32, 0x2d, 0xf6, 0x64,
	0x97, 0x94, 0x79, 0x1e, 0x30, 0x6d, 0x7e, 0x3d, 0x30, 0xc8, 0x3f, 0x81, 0xbb, 0x67, 0x69, 0xcc,
	0x68, 0xb8, 0x83, 0x7f, 0x6d, 0x13, 0x0f, 0xdc, 0xed, 0x26, 0xf9, 0xd5, 0x5e, 0xfe, 0x6d, 0x43,
	0x5f, 0x95, 0x3f, 0x21, 0x5f, 0x46, 0x33, 0x24, 0x9f, 0xa1, 0x6f, 0xde, 0xe1, 0x5d, 0x32, 0x67,
	0xe4, 0xc1, 0xb4, 0xe2, 0x5b, 0x9e, 0xae, 0x7f, 0xc8, 0xde, 0xc3, 0x66, 0x91, 0x59, 0xe8, 0x1e,
	0xf9, 0x06, 0xb0, 0x4a, 0x17, 0x39, 0xaa, 0x3c, 0xb5, 0x95, 0x70, 0xef, 0xf1, 0x95, 0x3a, 0xdb,
	0x60, 0x95, 0xa4, 0x1a, 0x83, 0xad, 0x24, 0xd7, 0x18, 0x54, 0x44, 0x72, 0x8f, 0x7c, 0x81, 0x5e,
	0x19, 0x27, 0xf2, 0xa8, 0xf2, 0xdc, 0x66, 0x68, 0xbd, 0xa3, 0xab, 0x64, 0x65, 0xf7, 0x1f, 0x70,
	0x63, 0x2d, 0x3f, 0xe4, 0x49, 0xd3, 0x60, 0xd7, 0xd2, 0xe0, 0x3d, 0xdd, 0x45, 0x5a, 0x3a, 0x5d,
	0xc0, 0x60, 0x33, 0x11, 0xe4, 0x59, 0xf5, 0x3d, 0xab, 0xd3, 0xe7, 0x3d, 0xdf, 0x51, 0x5d, 0x58,
	0x9e, 0x77, 0xf5, 0x7f, 0xc3, 0xab, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xf6, 0xb8, 0xa2,
	0x34, 0x06, 0x00, 0x00,
}
