// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bottle/bottle.proto

package fullbottle_srv_bottle

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId               int64    `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	FolderId             int64    `protobuf:"varint,6,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{0}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FileInfo) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *FileInfo) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *FileInfo) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *FileInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *FileInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type FolderInfo struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64         `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreateTime           int64         `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64         `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Folders              []*FolderInfo `protobuf:"bytes,6,rep,name=folders,proto3" json:"folders,omitempty"`
	Files                []*FileInfo   `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FolderInfo) Reset()         { *m = FolderInfo{} }
func (m *FolderInfo) String() string { return proto.CompactTextString(m) }
func (*FolderInfo) ProtoMessage()    {}
func (*FolderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{1}
}

func (m *FolderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FolderInfo.Unmarshal(m, b)
}
func (m *FolderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FolderInfo.Marshal(b, m, deterministic)
}
func (m *FolderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FolderInfo.Merge(m, src)
}
func (m *FolderInfo) XXX_Size() int {
	return xxx_messageInfo_FolderInfo.Size(m)
}
func (m *FolderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FolderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FolderInfo proto.InternalMessageInfo

func (m *FolderInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FolderInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FolderInfo) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *FolderInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *FolderInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *FolderInfo) GetFolders() []*FolderInfo {
	if m != nil {
		return m.Folders
	}
	return nil
}

func (m *FolderInfo) GetFiles() []*FileInfo {
	if m != nil {
		return m.Files
	}
	return nil
}

type GetBottleMetadataRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBottleMetadataRequest) Reset()         { *m = GetBottleMetadataRequest{} }
func (m *GetBottleMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetBottleMetadataRequest) ProtoMessage()    {}
func (*GetBottleMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{2}
}

func (m *GetBottleMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBottleMetadataRequest.Unmarshal(m, b)
}
func (m *GetBottleMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBottleMetadataRequest.Marshal(b, m, deterministic)
}
func (m *GetBottleMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBottleMetadataRequest.Merge(m, src)
}
func (m *GetBottleMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetBottleMetadataRequest.Size(m)
}
func (m *GetBottleMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBottleMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBottleMetadataRequest proto.InternalMessageInfo

func (m *GetBottleMetadataRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetBottleMetadataResponse struct {
	Bid                  int64    `protobuf:"varint,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Capacity             int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Remain               int64    `protobuf:"varint,3,opt,name=remain,proto3" json:"remain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBottleMetadataResponse) Reset()         { *m = GetBottleMetadataResponse{} }
func (m *GetBottleMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetBottleMetadataResponse) ProtoMessage()    {}
func (*GetBottleMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{3}
}

func (m *GetBottleMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBottleMetadataResponse.Unmarshal(m, b)
}
func (m *GetBottleMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBottleMetadataResponse.Marshal(b, m, deterministic)
}
func (m *GetBottleMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBottleMetadataResponse.Merge(m, src)
}
func (m *GetBottleMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetBottleMetadataResponse.Size(m)
}
func (m *GetBottleMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBottleMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBottleMetadataResponse proto.InternalMessageInfo

func (m *GetBottleMetadataResponse) GetBid() int64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *GetBottleMetadataResponse) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *GetBottleMetadataResponse) GetRemain() int64 {
	if m != nil {
		return m.Remain
	}
	return 0
}

type InitBottleRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Capacity             int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitBottleRequest) Reset()         { *m = InitBottleRequest{} }
func (m *InitBottleRequest) String() string { return proto.CompactTextString(m) }
func (*InitBottleRequest) ProtoMessage()    {}
func (*InitBottleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{4}
}

func (m *InitBottleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBottleRequest.Unmarshal(m, b)
}
func (m *InitBottleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBottleRequest.Marshal(b, m, deterministic)
}
func (m *InitBottleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBottleRequest.Merge(m, src)
}
func (m *InitBottleRequest) XXX_Size() int {
	return xxx_messageInfo_InitBottleRequest.Size(m)
}
func (m *InitBottleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBottleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitBottleRequest proto.InternalMessageInfo

func (m *InitBottleRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InitBottleRequest) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type InitBottleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitBottleResponse) Reset()         { *m = InitBottleResponse{} }
func (m *InitBottleResponse) String() string { return proto.CompactTextString(m) }
func (*InitBottleResponse) ProtoMessage()    {}
func (*InitBottleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{5}
}

func (m *InitBottleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBottleResponse.Unmarshal(m, b)
}
func (m *InitBottleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBottleResponse.Marshal(b, m, deterministic)
}
func (m *InitBottleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBottleResponse.Merge(m, src)
}
func (m *InitBottleResponse) XXX_Size() int {
	return xxx_messageInfo_InitBottleResponse.Size(m)
}
func (m *InitBottleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBottleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitBottleResponse proto.InternalMessageInfo

type UpdateBottleRequest struct {
	Bid                  int64    `protobuf:"varint,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Capacity             int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBottleRequest) Reset()         { *m = UpdateBottleRequest{} }
func (m *UpdateBottleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBottleRequest) ProtoMessage()    {}
func (*UpdateBottleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{6}
}

func (m *UpdateBottleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBottleRequest.Unmarshal(m, b)
}
func (m *UpdateBottleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBottleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBottleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBottleRequest.Merge(m, src)
}
func (m *UpdateBottleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBottleRequest.Size(m)
}
func (m *UpdateBottleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBottleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBottleRequest proto.InternalMessageInfo

func (m *UpdateBottleRequest) GetBid() int64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *UpdateBottleRequest) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type UpdateBottleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBottleResponse) Reset()         { *m = UpdateBottleResponse{} }
func (m *UpdateBottleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBottleResponse) ProtoMessage()    {}
func (*UpdateBottleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{7}
}

func (m *UpdateBottleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBottleResponse.Unmarshal(m, b)
}
func (m *UpdateBottleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBottleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBottleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBottleResponse.Merge(m, src)
}
func (m *UpdateBottleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBottleResponse.Size(m)
}
func (m *UpdateBottleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBottleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBottleResponse proto.InternalMessageInfo

type GetFolderInfoRequest struct {
	// Types that are valid to be assigned to Ident:
	//	*GetFolderInfoRequest_FolderId
	//	*GetFolderInfoRequest_Path_
	Ident                isGetFolderInfoRequest_Ident `protobuf_oneof:"ident"`
	OwnerId              int64                        `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetFolderInfoRequest) Reset()         { *m = GetFolderInfoRequest{} }
func (m *GetFolderInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetFolderInfoRequest) ProtoMessage()    {}
func (*GetFolderInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{8}
}

func (m *GetFolderInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFolderInfoRequest.Unmarshal(m, b)
}
func (m *GetFolderInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFolderInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetFolderInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFolderInfoRequest.Merge(m, src)
}
func (m *GetFolderInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetFolderInfoRequest.Size(m)
}
func (m *GetFolderInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFolderInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFolderInfoRequest proto.InternalMessageInfo

type isGetFolderInfoRequest_Ident interface {
	isGetFolderInfoRequest_Ident()
}

type GetFolderInfoRequest_FolderId struct {
	FolderId int64 `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3,oneof"`
}

type GetFolderInfoRequest_Path_ struct {
	Path *GetFolderInfoRequest_Path `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

func (*GetFolderInfoRequest_FolderId) isGetFolderInfoRequest_Ident() {}

func (*GetFolderInfoRequest_Path_) isGetFolderInfoRequest_Ident() {}

func (m *GetFolderInfoRequest) GetIdent() isGetFolderInfoRequest_Ident {
	if m != nil {
		return m.Ident
	}
	return nil
}

func (m *GetFolderInfoRequest) GetFolderId() int64 {
	if x, ok := m.GetIdent().(*GetFolderInfoRequest_FolderId); ok {
		return x.FolderId
	}
	return 0
}

func (m *GetFolderInfoRequest) GetPath() *GetFolderInfoRequest_Path {
	if x, ok := m.GetIdent().(*GetFolderInfoRequest_Path_); ok {
		return x.Path
	}
	return nil
}

func (m *GetFolderInfoRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetFolderInfoRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetFolderInfoRequest_FolderId)(nil),
		(*GetFolderInfoRequest_Path_)(nil),
	}
}

type GetFolderInfoRequest_Path struct {
	Relative             string   `protobuf:"bytes,1,opt,name=relative,proto3" json:"relative,omitempty"`
	BaseFolder           int64    `protobuf:"varint,2,opt,name=base_folder,json=baseFolder,proto3" json:"base_folder,omitempty"`
	FilterFolders        []int64  `protobuf:"varint,3,rep,packed,name=filter_folders,json=filterFolders,proto3" json:"filter_folders,omitempty"`
	FilterFiles          []int64  `protobuf:"varint,4,rep,packed,name=filter_files,json=filterFiles,proto3" json:"filter_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFolderInfoRequest_Path) Reset()         { *m = GetFolderInfoRequest_Path{} }
func (m *GetFolderInfoRequest_Path) String() string { return proto.CompactTextString(m) }
func (*GetFolderInfoRequest_Path) ProtoMessage()    {}
func (*GetFolderInfoRequest_Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{8, 0}
}

func (m *GetFolderInfoRequest_Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFolderInfoRequest_Path.Unmarshal(m, b)
}
func (m *GetFolderInfoRequest_Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFolderInfoRequest_Path.Marshal(b, m, deterministic)
}
func (m *GetFolderInfoRequest_Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFolderInfoRequest_Path.Merge(m, src)
}
func (m *GetFolderInfoRequest_Path) XXX_Size() int {
	return xxx_messageInfo_GetFolderInfoRequest_Path.Size(m)
}
func (m *GetFolderInfoRequest_Path) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFolderInfoRequest_Path.DiscardUnknown(m)
}

var xxx_messageInfo_GetFolderInfoRequest_Path proto.InternalMessageInfo

func (m *GetFolderInfoRequest_Path) GetRelative() string {
	if m != nil {
		return m.Relative
	}
	return ""
}

func (m *GetFolderInfoRequest_Path) GetBaseFolder() int64 {
	if m != nil {
		return m.BaseFolder
	}
	return 0
}

func (m *GetFolderInfoRequest_Path) GetFilterFolders() []int64 {
	if m != nil {
		return m.FilterFolders
	}
	return nil
}

func (m *GetFolderInfoRequest_Path) GetFilterFiles() []int64 {
	if m != nil {
		return m.FilterFiles
	}
	return nil
}

type GetFolderInfoResponse struct {
	Folder               *FolderInfo `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetFolderInfoResponse) Reset()         { *m = GetFolderInfoResponse{} }
func (m *GetFolderInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetFolderInfoResponse) ProtoMessage()    {}
func (*GetFolderInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{9}
}

func (m *GetFolderInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFolderInfoResponse.Unmarshal(m, b)
}
func (m *GetFolderInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFolderInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetFolderInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFolderInfoResponse.Merge(m, src)
}
func (m *GetFolderInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetFolderInfoResponse.Size(m)
}
func (m *GetFolderInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFolderInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFolderInfoResponse proto.InternalMessageInfo

func (m *GetFolderInfoResponse) GetFolder() *FolderInfo {
	if m != nil {
		return m.Folder
	}
	return nil
}

type CreateFolderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64    `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFolderRequest) Reset()         { *m = CreateFolderRequest{} }
func (m *CreateFolderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFolderRequest) ProtoMessage()    {}
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{10}
}

func (m *CreateFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFolderRequest.Unmarshal(m, b)
}
func (m *CreateFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFolderRequest.Marshal(b, m, deterministic)
}
func (m *CreateFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFolderRequest.Merge(m, src)
}
func (m *CreateFolderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFolderRequest.Size(m)
}
func (m *CreateFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFolderRequest proto.InternalMessageInfo

func (m *CreateFolderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFolderRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CreateFolderRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type CreateFolderResponse struct {
	FolderId             int64    `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFolderResponse) Reset()         { *m = CreateFolderResponse{} }
func (m *CreateFolderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFolderResponse) ProtoMessage()    {}
func (*CreateFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{11}
}

func (m *CreateFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFolderResponse.Unmarshal(m, b)
}
func (m *CreateFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFolderResponse.Marshal(b, m, deterministic)
}
func (m *CreateFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFolderResponse.Merge(m, src)
}
func (m *CreateFolderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFolderResponse.Size(m)
}
func (m *CreateFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFolderResponse proto.InternalMessageInfo

func (m *CreateFolderResponse) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

type UpdateFolderRequest struct {
	FolderId             int64    `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFolderRequest) Reset()         { *m = UpdateFolderRequest{} }
func (m *UpdateFolderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFolderRequest) ProtoMessage()    {}
func (*UpdateFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{12}
}

func (m *UpdateFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFolderRequest.Unmarshal(m, b)
}
func (m *UpdateFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFolderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFolderRequest.Merge(m, src)
}
func (m *UpdateFolderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFolderRequest.Size(m)
}
func (m *UpdateFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFolderRequest proto.InternalMessageInfo

func (m *UpdateFolderRequest) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *UpdateFolderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateFolderRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *UpdateFolderRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type UpdateFolderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFolderResponse) Reset()         { *m = UpdateFolderResponse{} }
func (m *UpdateFolderResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFolderResponse) ProtoMessage()    {}
func (*UpdateFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{13}
}

func (m *UpdateFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFolderResponse.Unmarshal(m, b)
}
func (m *UpdateFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFolderResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFolderResponse.Merge(m, src)
}
func (m *UpdateFolderResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFolderResponse.Size(m)
}
func (m *UpdateFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFolderResponse proto.InternalMessageInfo

type RemoveFolderRequest struct {
	FolderId             int64    `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFolderRequest) Reset()         { *m = RemoveFolderRequest{} }
func (m *RemoveFolderRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFolderRequest) ProtoMessage()    {}
func (*RemoveFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{14}
}

func (m *RemoveFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFolderRequest.Unmarshal(m, b)
}
func (m *RemoveFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFolderRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFolderRequest.Merge(m, src)
}
func (m *RemoveFolderRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFolderRequest.Size(m)
}
func (m *RemoveFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFolderRequest proto.InternalMessageInfo

func (m *RemoveFolderRequest) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *RemoveFolderRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type RemoveFolderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFolderResponse) Reset()         { *m = RemoveFolderResponse{} }
func (m *RemoveFolderResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFolderResponse) ProtoMessage()    {}
func (*RemoveFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{15}
}

func (m *RemoveFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFolderResponse.Unmarshal(m, b)
}
func (m *RemoveFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFolderResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFolderResponse.Merge(m, src)
}
func (m *RemoveFolderResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFolderResponse.Size(m)
}
func (m *RemoveFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFolderResponse proto.InternalMessageInfo

type GetFileMetaRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileMetaRequest) Reset()         { *m = GetFileMetaRequest{} }
func (m *GetFileMetaRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileMetaRequest) ProtoMessage()    {}
func (*GetFileMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{16}
}

func (m *GetFileMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileMetaRequest.Unmarshal(m, b)
}
func (m *GetFileMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileMetaRequest.Marshal(b, m, deterministic)
}
func (m *GetFileMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileMetaRequest.Merge(m, src)
}
func (m *GetFileMetaRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileMetaRequest.Size(m)
}
func (m *GetFileMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileMetaRequest proto.InternalMessageInfo

func (m *GetFileMetaRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetFileMetaResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fid                  string   `protobuf:"bytes,2,opt,name=fid,proto3" json:"fid,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	ChunkManifest        string   `protobuf:"bytes,5,opt,name=chunk_manifest,json=chunkManifest,proto3" json:"chunk_manifest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileMetaResponse) Reset()         { *m = GetFileMetaResponse{} }
func (m *GetFileMetaResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileMetaResponse) ProtoMessage()    {}
func (*GetFileMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{17}
}

func (m *GetFileMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileMetaResponse.Unmarshal(m, b)
}
func (m *GetFileMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileMetaResponse.Marshal(b, m, deterministic)
}
func (m *GetFileMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileMetaResponse.Merge(m, src)
}
func (m *GetFileMetaResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileMetaResponse.Size(m)
}
func (m *GetFileMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileMetaResponse proto.InternalMessageInfo

func (m *GetFileMetaResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetFileMetaResponse) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *GetFileMetaResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetFileMetaResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *GetFileMetaResponse) GetChunkManifest() string {
	if m != nil {
		return m.ChunkManifest
	}
	return ""
}

type CreateFileMetaRequest struct {
	Fid                  string   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	ChunkManifest        string   `protobuf:"bytes,4,opt,name=chunk_manifest,json=chunkManifest,proto3" json:"chunk_manifest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileMetaRequest) Reset()         { *m = CreateFileMetaRequest{} }
func (m *CreateFileMetaRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFileMetaRequest) ProtoMessage()    {}
func (*CreateFileMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{18}
}

func (m *CreateFileMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileMetaRequest.Unmarshal(m, b)
}
func (m *CreateFileMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileMetaRequest.Marshal(b, m, deterministic)
}
func (m *CreateFileMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileMetaRequest.Merge(m, src)
}
func (m *CreateFileMetaRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFileMetaRequest.Size(m)
}
func (m *CreateFileMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileMetaRequest proto.InternalMessageInfo

func (m *CreateFileMetaRequest) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *CreateFileMetaRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateFileMetaRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CreateFileMetaRequest) GetChunkManifest() string {
	if m != nil {
		return m.ChunkManifest
	}
	return ""
}

type CreateFileMetaResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileMetaResponse) Reset()         { *m = CreateFileMetaResponse{} }
func (m *CreateFileMetaResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFileMetaResponse) ProtoMessage()    {}
func (*CreateFileMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{19}
}

func (m *CreateFileMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileMetaResponse.Unmarshal(m, b)
}
func (m *CreateFileMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileMetaResponse.Marshal(b, m, deterministic)
}
func (m *CreateFileMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileMetaResponse.Merge(m, src)
}
func (m *CreateFileMetaResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFileMetaResponse.Size(m)
}
func (m *CreateFileMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileMetaResponse proto.InternalMessageInfo

func (m *CreateFileMetaResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetFileInfoRequest struct {
	FileId               int64    `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileInfoRequest) Reset()         { *m = GetFileInfoRequest{} }
func (m *GetFileInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileInfoRequest) ProtoMessage()    {}
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{20}
}

func (m *GetFileInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileInfoRequest.Unmarshal(m, b)
}
func (m *GetFileInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetFileInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileInfoRequest.Merge(m, src)
}
func (m *GetFileInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileInfoRequest.Size(m)
}
func (m *GetFileInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileInfoRequest proto.InternalMessageInfo

func (m *GetFileInfoRequest) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *GetFileInfoRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type GetFileInfoResponse struct {
	File                 *FileInfo `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetFileInfoResponse) Reset()         { *m = GetFileInfoResponse{} }
func (m *GetFileInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileInfoResponse) ProtoMessage()    {}
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{21}
}

func (m *GetFileInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileInfoResponse.Unmarshal(m, b)
}
func (m *GetFileInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetFileInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileInfoResponse.Merge(m, src)
}
func (m *GetFileInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileInfoResponse.Size(m)
}
func (m *GetFileInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileInfoResponse proto.InternalMessageInfo

func (m *GetFileInfoResponse) GetFile() *FileInfo {
	if m != nil {
		return m.File
	}
	return nil
}

type GetFileByMetaRequest struct {
	MetaId               int64    `protobuf:"varint,1,opt,name=meta_id,json=metaId,proto3" json:"meta_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FolderId             int64    `protobuf:"varint,3,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileByMetaRequest) Reset()         { *m = GetFileByMetaRequest{} }
func (m *GetFileByMetaRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileByMetaRequest) ProtoMessage()    {}
func (*GetFileByMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{22}
}

func (m *GetFileByMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileByMetaRequest.Unmarshal(m, b)
}
func (m *GetFileByMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileByMetaRequest.Marshal(b, m, deterministic)
}
func (m *GetFileByMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileByMetaRequest.Merge(m, src)
}
func (m *GetFileByMetaRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileByMetaRequest.Size(m)
}
func (m *GetFileByMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileByMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileByMetaRequest proto.InternalMessageInfo

func (m *GetFileByMetaRequest) GetMetaId() int64 {
	if m != nil {
		return m.MetaId
	}
	return 0
}

func (m *GetFileByMetaRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *GetFileByMetaRequest) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *GetFileByMetaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetFileByMetaResponse struct {
	File                 *FileInfo `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetFileByMetaResponse) Reset()         { *m = GetFileByMetaResponse{} }
func (m *GetFileByMetaResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileByMetaResponse) ProtoMessage()    {}
func (*GetFileByMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{23}
}

func (m *GetFileByMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileByMetaResponse.Unmarshal(m, b)
}
func (m *GetFileByMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileByMetaResponse.Marshal(b, m, deterministic)
}
func (m *GetFileByMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileByMetaResponse.Merge(m, src)
}
func (m *GetFileByMetaResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileByMetaResponse.Size(m)
}
func (m *GetFileByMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileByMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileByMetaResponse proto.InternalMessageInfo

func (m *GetFileByMetaResponse) GetFile() *FileInfo {
	if m != nil {
		return m.File
	}
	return nil
}

type CreateFileRequest struct {
	OwnerId              int64    `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FolderId             int64    `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MetaId               int64    `protobuf:"varint,4,opt,name=meta_id,json=metaId,proto3" json:"meta_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileRequest) Reset()         { *m = CreateFileRequest{} }
func (m *CreateFileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFileRequest) ProtoMessage()    {}
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{24}
}

func (m *CreateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileRequest.Unmarshal(m, b)
}
func (m *CreateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileRequest.Marshal(b, m, deterministic)
}
func (m *CreateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileRequest.Merge(m, src)
}
func (m *CreateFileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFileRequest.Size(m)
}
func (m *CreateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileRequest proto.InternalMessageInfo

func (m *CreateFileRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *CreateFileRequest) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *CreateFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFileRequest) GetMetaId() int64 {
	if m != nil {
		return m.MetaId
	}
	return 0
}

type CreateFileResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileResponse) Reset()         { *m = CreateFileResponse{} }
func (m *CreateFileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFileResponse) ProtoMessage()    {}
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{25}
}

func (m *CreateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileResponse.Unmarshal(m, b)
}
func (m *CreateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileResponse.Marshal(b, m, deterministic)
}
func (m *CreateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileResponse.Merge(m, src)
}
func (m *CreateFileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFileResponse.Size(m)
}
func (m *CreateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileResponse proto.InternalMessageInfo

func (m *CreateFileResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateFileRequest struct {
	FileId  int64 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId int64 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// form
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FolderId             int64    `protobuf:"varint,4,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileRequest) Reset()         { *m = UpdateFileRequest{} }
func (m *UpdateFileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFileRequest) ProtoMessage()    {}
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{26}
}

func (m *UpdateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileRequest.Unmarshal(m, b)
}
func (m *UpdateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileRequest.Merge(m, src)
}
func (m *UpdateFileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFileRequest.Size(m)
}
func (m *UpdateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileRequest proto.InternalMessageInfo

func (m *UpdateFileRequest) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *UpdateFileRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *UpdateFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateFileRequest) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

type UpdateFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileResponse) Reset()         { *m = UpdateFileResponse{} }
func (m *UpdateFileResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFileResponse) ProtoMessage()    {}
func (*UpdateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{27}
}

func (m *UpdateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileResponse.Unmarshal(m, b)
}
func (m *UpdateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileResponse.Merge(m, src)
}
func (m *UpdateFileResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFileResponse.Size(m)
}
func (m *UpdateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileResponse proto.InternalMessageInfo

type RemoveFileRequest struct {
	FileId               int64    `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFileRequest) Reset()         { *m = RemoveFileRequest{} }
func (m *RemoveFileRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFileRequest) ProtoMessage()    {}
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{28}
}

func (m *RemoveFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFileRequest.Unmarshal(m, b)
}
func (m *RemoveFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFileRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFileRequest.Merge(m, src)
}
func (m *RemoveFileRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFileRequest.Size(m)
}
func (m *RemoveFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFileRequest proto.InternalMessageInfo

func (m *RemoveFileRequest) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *RemoveFileRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type RemoveFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFileResponse) Reset()         { *m = RemoveFileResponse{} }
func (m *RemoveFileResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFileResponse) ProtoMessage()    {}
func (*RemoveFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{29}
}

func (m *RemoveFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFileResponse.Unmarshal(m, b)
}
func (m *RemoveFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFileResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFileResponse.Merge(m, src)
}
func (m *RemoveFileResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFileResponse.Size(m)
}
func (m *RemoveFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFileResponse proto.InternalMessageInfo

type CreateDownloadUrlRequest struct {
	FileId               int64    `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDownloadUrlRequest) Reset()         { *m = CreateDownloadUrlRequest{} }
func (m *CreateDownloadUrlRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDownloadUrlRequest) ProtoMessage()    {}
func (*CreateDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{30}
}

func (m *CreateDownloadUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDownloadUrlRequest.Unmarshal(m, b)
}
func (m *CreateDownloadUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDownloadUrlRequest.Marshal(b, m, deterministic)
}
func (m *CreateDownloadUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDownloadUrlRequest.Merge(m, src)
}
func (m *CreateDownloadUrlRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDownloadUrlRequest.Size(m)
}
func (m *CreateDownloadUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDownloadUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDownloadUrlRequest proto.InternalMessageInfo

func (m *CreateDownloadUrlRequest) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *CreateDownloadUrlRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *CreateDownloadUrlRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateDownloadUrlResponse struct {
	DownloadToken        string   `protobuf:"bytes,1,opt,name=download_token,json=downloadToken,proto3" json:"download_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDownloadUrlResponse) Reset()         { *m = CreateDownloadUrlResponse{} }
func (m *CreateDownloadUrlResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDownloadUrlResponse) ProtoMessage()    {}
func (*CreateDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{31}
}

func (m *CreateDownloadUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDownloadUrlResponse.Unmarshal(m, b)
}
func (m *CreateDownloadUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDownloadUrlResponse.Marshal(b, m, deterministic)
}
func (m *CreateDownloadUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDownloadUrlResponse.Merge(m, src)
}
func (m *CreateDownloadUrlResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDownloadUrlResponse.Size(m)
}
func (m *CreateDownloadUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDownloadUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDownloadUrlResponse proto.InternalMessageInfo

func (m *CreateDownloadUrlResponse) GetDownloadToken() string {
	if m != nil {
		return m.DownloadToken
	}
	return ""
}

type GetWeedDownloadUrlRequest struct {
	DownloadToken        string   `protobuf:"bytes,1,opt,name=download_token,json=downloadToken,proto3" json:"download_token,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWeedDownloadUrlRequest) Reset()         { *m = GetWeedDownloadUrlRequest{} }
func (m *GetWeedDownloadUrlRequest) String() string { return proto.CompactTextString(m) }
func (*GetWeedDownloadUrlRequest) ProtoMessage()    {}
func (*GetWeedDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{32}
}

func (m *GetWeedDownloadUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWeedDownloadUrlRequest.Unmarshal(m, b)
}
func (m *GetWeedDownloadUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWeedDownloadUrlRequest.Marshal(b, m, deterministic)
}
func (m *GetWeedDownloadUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWeedDownloadUrlRequest.Merge(m, src)
}
func (m *GetWeedDownloadUrlRequest) XXX_Size() int {
	return xxx_messageInfo_GetWeedDownloadUrlRequest.Size(m)
}
func (m *GetWeedDownloadUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWeedDownloadUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWeedDownloadUrlRequest proto.InternalMessageInfo

func (m *GetWeedDownloadUrlRequest) GetDownloadToken() string {
	if m != nil {
		return m.DownloadToken
	}
	return ""
}

func (m *GetWeedDownloadUrlRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetWeedDownloadUrlResponse struct {
	WeedUrl              string   `protobuf:"bytes,1,opt,name=weed_url,json=weedUrl,proto3" json:"weed_url,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWeedDownloadUrlResponse) Reset()         { *m = GetWeedDownloadUrlResponse{} }
func (m *GetWeedDownloadUrlResponse) String() string { return proto.CompactTextString(m) }
func (*GetWeedDownloadUrlResponse) ProtoMessage()    {}
func (*GetWeedDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{33}
}

func (m *GetWeedDownloadUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWeedDownloadUrlResponse.Unmarshal(m, b)
}
func (m *GetWeedDownloadUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWeedDownloadUrlResponse.Marshal(b, m, deterministic)
}
func (m *GetWeedDownloadUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWeedDownloadUrlResponse.Merge(m, src)
}
func (m *GetWeedDownloadUrlResponse) XXX_Size() int {
	return xxx_messageInfo_GetWeedDownloadUrlResponse.Size(m)
}
func (m *GetWeedDownloadUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWeedDownloadUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWeedDownloadUrlResponse proto.InternalMessageInfo

func (m *GetWeedDownloadUrlResponse) GetWeedUrl() string {
	if m != nil {
		return m.WeedUrl
	}
	return ""
}

func (m *GetWeedDownloadUrlResponse) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type GetImageThumbnailRequest struct {
	FileId               int64    `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetImageThumbnailRequest) Reset()         { *m = GetImageThumbnailRequest{} }
func (m *GetImageThumbnailRequest) String() string { return proto.CompactTextString(m) }
func (*GetImageThumbnailRequest) ProtoMessage()    {}
func (*GetImageThumbnailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{34}
}

func (m *GetImageThumbnailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImageThumbnailRequest.Unmarshal(m, b)
}
func (m *GetImageThumbnailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImageThumbnailRequest.Marshal(b, m, deterministic)
}
func (m *GetImageThumbnailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImageThumbnailRequest.Merge(m, src)
}
func (m *GetImageThumbnailRequest) XXX_Size() int {
	return xxx_messageInfo_GetImageThumbnailRequest.Size(m)
}
func (m *GetImageThumbnailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImageThumbnailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetImageThumbnailRequest proto.InternalMessageInfo

func (m *GetImageThumbnailRequest) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *GetImageThumbnailRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *GetImageThumbnailRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetImageThumbnailRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetImageThumbnailRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type GetImageThumbnailResponse struct {
	Thumbnail            []byte   `protobuf:"bytes,1,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetImageThumbnailResponse) Reset()         { *m = GetImageThumbnailResponse{} }
func (m *GetImageThumbnailResponse) String() string { return proto.CompactTextString(m) }
func (*GetImageThumbnailResponse) ProtoMessage()    {}
func (*GetImageThumbnailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{35}
}

func (m *GetImageThumbnailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetImageThumbnailResponse.Unmarshal(m, b)
}
func (m *GetImageThumbnailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetImageThumbnailResponse.Marshal(b, m, deterministic)
}
func (m *GetImageThumbnailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetImageThumbnailResponse.Merge(m, src)
}
func (m *GetImageThumbnailResponse) XXX_Size() int {
	return xxx_messageInfo_GetImageThumbnailResponse.Size(m)
}
func (m *GetImageThumbnailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetImageThumbnailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetImageThumbnailResponse proto.InternalMessageInfo

func (m *GetImageThumbnailResponse) GetThumbnail() []byte {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

type ValidateEntryRequest struct {
	FileIds              []int64  `protobuf:"varint,1,rep,packed,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	FolderIds            []int64  `protobuf:"varint,2,rep,packed,name=folder_ids,json=folderIds,proto3" json:"folder_ids,omitempty"`
	OwnerId              int64    `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ParentId             int64    `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEntryRequest) Reset()         { *m = ValidateEntryRequest{} }
func (m *ValidateEntryRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateEntryRequest) ProtoMessage()    {}
func (*ValidateEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{36}
}

func (m *ValidateEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEntryRequest.Unmarshal(m, b)
}
func (m *ValidateEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEntryRequest.Marshal(b, m, deterministic)
}
func (m *ValidateEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEntryRequest.Merge(m, src)
}
func (m *ValidateEntryRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateEntryRequest.Size(m)
}
func (m *ValidateEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEntryRequest proto.InternalMessageInfo

func (m *ValidateEntryRequest) GetFileIds() []int64 {
	if m != nil {
		return m.FileIds
	}
	return nil
}

func (m *ValidateEntryRequest) GetFolderIds() []int64 {
	if m != nil {
		return m.FolderIds
	}
	return nil
}

func (m *ValidateEntryRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *ValidateEntryRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type ValidateEntryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEntryResponse) Reset()         { *m = ValidateEntryResponse{} }
func (m *ValidateEntryResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateEntryResponse) ProtoMessage()    {}
func (*ValidateEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{37}
}

func (m *ValidateEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEntryResponse.Unmarshal(m, b)
}
func (m *ValidateEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEntryResponse.Marshal(b, m, deterministic)
}
func (m *ValidateEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEntryResponse.Merge(m, src)
}
func (m *ValidateEntryResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateEntryResponse.Size(m)
}
func (m *ValidateEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEntryResponse proto.InternalMessageInfo

type GetEntryParentsRequest struct {
	// Types that are valid to be assigned to EntryId:
	//	*GetEntryParentsRequest_FolderId
	//	*GetEntryParentsRequest_FileId
	EntryId              isGetEntryParentsRequest_EntryId `protobuf_oneof:"entry_id"`
	OwnerId              int64                            `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetEntryParentsRequest) Reset()         { *m = GetEntryParentsRequest{} }
func (m *GetEntryParentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntryParentsRequest) ProtoMessage()    {}
func (*GetEntryParentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{38}
}

func (m *GetEntryParentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntryParentsRequest.Unmarshal(m, b)
}
func (m *GetEntryParentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntryParentsRequest.Marshal(b, m, deterministic)
}
func (m *GetEntryParentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntryParentsRequest.Merge(m, src)
}
func (m *GetEntryParentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntryParentsRequest.Size(m)
}
func (m *GetEntryParentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntryParentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntryParentsRequest proto.InternalMessageInfo

type isGetEntryParentsRequest_EntryId interface {
	isGetEntryParentsRequest_EntryId()
}

type GetEntryParentsRequest_FolderId struct {
	FolderId int64 `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3,oneof"`
}

type GetEntryParentsRequest_FileId struct {
	FileId int64 `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3,oneof"`
}

func (*GetEntryParentsRequest_FolderId) isGetEntryParentsRequest_EntryId() {}

func (*GetEntryParentsRequest_FileId) isGetEntryParentsRequest_EntryId() {}

func (m *GetEntryParentsRequest) GetEntryId() isGetEntryParentsRequest_EntryId {
	if m != nil {
		return m.EntryId
	}
	return nil
}

func (m *GetEntryParentsRequest) GetFolderId() int64 {
	if x, ok := m.GetEntryId().(*GetEntryParentsRequest_FolderId); ok {
		return x.FolderId
	}
	return 0
}

func (m *GetEntryParentsRequest) GetFileId() int64 {
	if x, ok := m.GetEntryId().(*GetEntryParentsRequest_FileId); ok {
		return x.FileId
	}
	return 0
}

func (m *GetEntryParentsRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetEntryParentsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetEntryParentsRequest_FolderId)(nil),
		(*GetEntryParentsRequest_FileId)(nil),
	}
}

type GetEntryParentsResponse struct {
	Parents              []*GetEntryParentsResponseSimpleParent `protobuf:"bytes,1,rep,name=parents,proto3" json:"parents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetEntryParentsResponse) Reset()         { *m = GetEntryParentsResponse{} }
func (m *GetEntryParentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntryParentsResponse) ProtoMessage()    {}
func (*GetEntryParentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{39}
}

func (m *GetEntryParentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntryParentsResponse.Unmarshal(m, b)
}
func (m *GetEntryParentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntryParentsResponse.Marshal(b, m, deterministic)
}
func (m *GetEntryParentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntryParentsResponse.Merge(m, src)
}
func (m *GetEntryParentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntryParentsResponse.Size(m)
}
func (m *GetEntryParentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntryParentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntryParentsResponse proto.InternalMessageInfo

func (m *GetEntryParentsResponse) GetParents() []*GetEntryParentsResponseSimpleParent {
	if m != nil {
		return m.Parents
	}
	return nil
}

type GetEntryParentsResponseSimpleParent struct {
	FolderId             int64    `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntryParentsResponseSimpleParent) Reset()         { *m = GetEntryParentsResponseSimpleParent{} }
func (m *GetEntryParentsResponseSimpleParent) String() string { return proto.CompactTextString(m) }
func (*GetEntryParentsResponseSimpleParent) ProtoMessage()    {}
func (*GetEntryParentsResponseSimpleParent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{39, 0}
}

func (m *GetEntryParentsResponseSimpleParent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntryParentsResponseSimpleParent.Unmarshal(m, b)
}
func (m *GetEntryParentsResponseSimpleParent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntryParentsResponseSimpleParent.Marshal(b, m, deterministic)
}
func (m *GetEntryParentsResponseSimpleParent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntryParentsResponseSimpleParent.Merge(m, src)
}
func (m *GetEntryParentsResponseSimpleParent) XXX_Size() int {
	return xxx_messageInfo_GetEntryParentsResponseSimpleParent.Size(m)
}
func (m *GetEntryParentsResponseSimpleParent) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntryParentsResponseSimpleParent.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntryParentsResponseSimpleParent proto.InternalMessageInfo

func (m *GetEntryParentsResponseSimpleParent) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *GetEntryParentsResponseSimpleParent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*FileInfo)(nil), "fullbottle.srv.bottle.FileInfo")
	proto.RegisterType((*FolderInfo)(nil), "fullbottle.srv.bottle.FolderInfo")
	proto.RegisterType((*GetBottleMetadataRequest)(nil), "fullbottle.srv.bottle.GetBottleMetadataRequest")
	proto.RegisterType((*GetBottleMetadataResponse)(nil), "fullbottle.srv.bottle.GetBottleMetadataResponse")
	proto.RegisterType((*InitBottleRequest)(nil), "fullbottle.srv.bottle.InitBottleRequest")
	proto.RegisterType((*InitBottleResponse)(nil), "fullbottle.srv.bottle.InitBottleResponse")
	proto.RegisterType((*UpdateBottleRequest)(nil), "fullbottle.srv.bottle.UpdateBottleRequest")
	proto.RegisterType((*UpdateBottleResponse)(nil), "fullbottle.srv.bottle.UpdateBottleResponse")
	proto.RegisterType((*GetFolderInfoRequest)(nil), "fullbottle.srv.bottle.GetFolderInfoRequest")
	proto.RegisterType((*GetFolderInfoRequest_Path)(nil), "fullbottle.srv.bottle.GetFolderInfoRequest.Path")
	proto.RegisterType((*GetFolderInfoResponse)(nil), "fullbottle.srv.bottle.GetFolderInfoResponse")
	proto.RegisterType((*CreateFolderRequest)(nil), "fullbottle.srv.bottle.CreateFolderRequest")
	proto.RegisterType((*CreateFolderResponse)(nil), "fullbottle.srv.bottle.CreateFolderResponse")
	proto.RegisterType((*UpdateFolderRequest)(nil), "fullbottle.srv.bottle.UpdateFolderRequest")
	proto.RegisterType((*UpdateFolderResponse)(nil), "fullbottle.srv.bottle.UpdateFolderResponse")
	proto.RegisterType((*RemoveFolderRequest)(nil), "fullbottle.srv.bottle.RemoveFolderRequest")
	proto.RegisterType((*RemoveFolderResponse)(nil), "fullbottle.srv.bottle.RemoveFolderResponse")
	proto.RegisterType((*GetFileMetaRequest)(nil), "fullbottle.srv.bottle.GetFileMetaRequest")
	proto.RegisterType((*GetFileMetaResponse)(nil), "fullbottle.srv.bottle.GetFileMetaResponse")
	proto.RegisterType((*CreateFileMetaRequest)(nil), "fullbottle.srv.bottle.CreateFileMetaRequest")
	proto.RegisterType((*CreateFileMetaResponse)(nil), "fullbottle.srv.bottle.CreateFileMetaResponse")
	proto.RegisterType((*GetFileInfoRequest)(nil), "fullbottle.srv.bottle.GetFileInfoRequest")
	proto.RegisterType((*GetFileInfoResponse)(nil), "fullbottle.srv.bottle.GetFileInfoResponse")
	proto.RegisterType((*GetFileByMetaRequest)(nil), "fullbottle.srv.bottle.GetFileByMetaRequest")
	proto.RegisterType((*GetFileByMetaResponse)(nil), "fullbottle.srv.bottle.GetFileByMetaResponse")
	proto.RegisterType((*CreateFileRequest)(nil), "fullbottle.srv.bottle.CreateFileRequest")
	proto.RegisterType((*CreateFileResponse)(nil), "fullbottle.srv.bottle.CreateFileResponse")
	proto.RegisterType((*UpdateFileRequest)(nil), "fullbottle.srv.bottle.UpdateFileRequest")
	proto.RegisterType((*UpdateFileResponse)(nil), "fullbottle.srv.bottle.UpdateFileResponse")
	proto.RegisterType((*RemoveFileRequest)(nil), "fullbottle.srv.bottle.RemoveFileRequest")
	proto.RegisterType((*RemoveFileResponse)(nil), "fullbottle.srv.bottle.RemoveFileResponse")
	proto.RegisterType((*CreateDownloadUrlRequest)(nil), "fullbottle.srv.bottle.CreateDownloadUrlRequest")
	proto.RegisterType((*CreateDownloadUrlResponse)(nil), "fullbottle.srv.bottle.CreateDownloadUrlResponse")
	proto.RegisterType((*GetWeedDownloadUrlRequest)(nil), "fullbottle.srv.bottle.GetWeedDownloadUrlRequest")
	proto.RegisterType((*GetWeedDownloadUrlResponse)(nil), "fullbottle.srv.bottle.GetWeedDownloadUrlResponse")
	proto.RegisterType((*GetImageThumbnailRequest)(nil), "fullbottle.srv.bottle.GetImageThumbnailRequest")
	proto.RegisterType((*GetImageThumbnailResponse)(nil), "fullbottle.srv.bottle.GetImageThumbnailResponse")
	proto.RegisterType((*ValidateEntryRequest)(nil), "fullbottle.srv.bottle.ValidateEntryRequest")
	proto.RegisterType((*ValidateEntryResponse)(nil), "fullbottle.srv.bottle.ValidateEntryResponse")
	proto.RegisterType((*GetEntryParentsRequest)(nil), "fullbottle.srv.bottle.GetEntryParentsRequest")
	proto.RegisterType((*GetEntryParentsResponse)(nil), "fullbottle.srv.bottle.GetEntryParentsResponse")
	proto.RegisterType((*GetEntryParentsResponseSimpleParent)(nil), "fullbottle.srv.bottle.GetEntryParentsResponse.simple_parent")
}

func init() { proto.RegisterFile("proto/bottle/bottle.proto", fileDescriptor_3f847e5351336bd8) }

var fileDescriptor_3f847e5351336bd8 = []byte{
	// 1482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0x16, 0x25, 0xea, 0x35, 0x8e, 0xdd, 0x78, 0x2d, 0xdb, 0xb2, 0xd2, 0x20, 0xce, 0xa2, 0x01,
	0x94, 0x97, 0x92, 0x3a, 0xe8, 0x21, 0x68, 0x0f, 0xad, 0xd3, 0xda, 0x56, 0xd1, 0x00, 0x01, 0xf3,
	0xe8, 0xa1, 0x07, 0x81, 0x36, 0x57, 0xd1, 0x22, 0x14, 0xa5, 0x92, 0x94, 0x1f, 0x0d, 0xd0, 0x4b,
	0x81, 0xa2, 0x97, 0x1e, 0xfb, 0x43, 0x8a, 0x9e, 0xfa, 0x93, 0xfa, 0x2f, 0x8a, 0x7d, 0x88, 0x5a,
	0x92, 0xbb, 0xb4, 0xdc, 0xa0, 0x27, 0x6b, 0x87, 0xb3, 0xf3, 0x7d, 0x33, 0x3b, 0xbb, 0xfb, 0xad,
	0x61, 0x67, 0x1a, 0x4e, 0xe2, 0xc9, 0xa3, 0xe3, 0x49, 0x1c, 0xfb, 0x44, 0xfe, 0xe9, 0x71, 0x1b,
	0xda, 0x1c, 0xce, 0x7c, 0x5f, 0x5a, 0xa2, 0xf0, 0xb4, 0x27, 0x7e, 0xe2, 0x7f, 0x2c, 0x68, 0x1c,
	0x50, 0x9f, 0xf4, 0x83, 0xe1, 0x04, 0xad, 0x41, 0x99, 0x7a, 0x6d, 0x6b, 0xd7, 0xea, 0x56, 0x9c,
	0x32, 0xf5, 0xd0, 0x36, 0xd4, 0x87, 0xd4, 0x27, 0x03, 0xea, 0xb5, 0xcb, 0xdc, 0x58, 0x63, 0xc3,
	0xbe, 0x87, 0x10, 0xd8, 0x81, 0x3b, 0x26, 0xed, 0xca, 0xae, 0xd5, 0x6d, 0x3a, 0xfc, 0x37, 0xb3,
	0x45, 0xf4, 0x27, 0xd2, 0xb6, 0xb9, 0x27, 0xff, 0xcd, 0x6c, 0x23, 0x37, 0x1a, 0xb5, 0xab, 0xc2,
	0x8f, 0xfd, 0x46, 0x37, 0xa0, 0x39, 0x9c, 0xf8, 0x1e, 0x09, 0x59, 0xd8, 0x1a, 0x77, 0x6e, 0x08,
	0x43, 0xdf, 0x43, 0x3b, 0xd0, 0x98, 0x9c, 0x05, 0xe2, 0x5b, 0x9d, 0x7f, 0xab, 0xf3, 0x71, 0xdf,
	0x43, 0xb7, 0x60, 0xe5, 0x24, 0x24, 0x6e, 0x4c, 0x06, 0x31, 0x1d, 0x93, 0x76, 0x83, 0x7f, 0x05,
	0x61, 0x7a, 0x45, 0xc7, 0x84, 0x39, 0xcc, 0xa6, 0x5e, 0xe2, 0xd0, 0x14, 0x0e, 0xc2, 0xc4, 0x1c,
	0xf0, 0x2f, 0x65, 0x80, 0x03, 0x81, 0xa4, 0xcb, 0x76, 0x9e, 0x54, 0x59, 0x49, 0xea, 0x06, 0x34,
	0xa7, 0x6e, 0x48, 0x82, 0x98, 0x11, 0xaa, 0x08, 0xb2, 0xc2, 0x90, 0x67, 0x64, 0x5f, 0xc6, 0xa8,
	0x9a, 0x65, 0x84, 0x3e, 0x87, 0xba, 0x48, 0x3d, 0x6a, 0xd7, 0x76, 0x2b, 0xdd, 0x95, 0xbd, 0xdb,
	0x3d, 0xed, 0x32, 0xf5, 0x16, 0xb4, 0x9d, 0xf9, 0x0c, 0xf4, 0x19, 0x54, 0xd9, 0x72, 0x44, 0xed,
	0x3a, 0x9f, 0x7a, 0xcb, 0x34, 0x55, 0xae, 0xae, 0x23, 0xbc, 0xf1, 0x03, 0x68, 0x1f, 0x92, 0x78,
	0x9f, 0x7f, 0x7c, 0x4e, 0x62, 0xd7, 0x73, 0x63, 0xd7, 0x21, 0x3f, 0xce, 0x48, 0x14, 0xa3, 0xeb,
	0x50, 0x99, 0x25, 0x35, 0x61, 0x3f, 0xb1, 0x0b, 0x3b, 0x1a, 0xef, 0x68, 0x3a, 0x09, 0x22, 0xc2,
	0xdc, 0x8f, 0x17, 0xee, 0xc7, 0xd4, 0x43, 0x1d, 0x68, 0x9c, 0xb8, 0x53, 0xf7, 0x84, 0xc6, 0x17,
	0xb2, 0x65, 0x92, 0x31, 0xda, 0x82, 0x5a, 0x48, 0xc6, 0x2e, 0x0d, 0x64, 0x21, 0xe5, 0x08, 0x7f,
	0x05, 0xeb, 0xfd, 0x80, 0x4a, 0x0c, 0x23, 0x93, 0xa2, 0xd0, 0xb8, 0x05, 0x48, 0x0d, 0x21, 0xe8,
	0xe1, 0x67, 0xb0, 0xf1, 0x9a, 0xd7, 0x3a, 0x17, 0x7a, 0x79, 0xd6, 0x78, 0x0b, 0x5a, 0xe9, 0x20,
	0x32, 0xf8, 0x9f, 0x65, 0x68, 0x1d, 0x92, 0x58, 0x59, 0x18, 0x19, 0xfe, 0xa6, 0xda, 0xdf, 0x1c,
	0xe4, 0xa8, 0xa4, 0x74, 0xf8, 0x01, 0xd8, 0x53, 0x37, 0x1e, 0x71, 0x9c, 0x95, 0xbd, 0xc7, 0x86,
	0x45, 0xd3, 0x45, 0xee, 0xbd, 0x70, 0xe3, 0xd1, 0x51, 0xc9, 0xe1, 0xf3, 0x53, 0x3b, 0xa5, 0x92,
	0xda, 0x29, 0x9d, 0xdf, 0x2d, 0xb0, 0x99, 0x2f, 0xcb, 0x2b, 0x24, 0xbe, 0x1b, 0xd3, 0x53, 0xc2,
	0x99, 0x34, 0x9d, 0x64, 0xcc, 0x7a, 0xf3, 0xd8, 0x8d, 0xc8, 0x40, 0x10, 0x93, 0x69, 0x03, 0x33,
	0x09, 0x60, 0x74, 0x07, 0xd6, 0x86, 0xd4, 0x8f, 0x49, 0x38, 0x98, 0xb7, 0x68, 0x65, 0xb7, 0xd2,
	0xad, 0x38, 0xab, 0xc2, 0x7a, 0x20, 0xbb, 0xf0, 0x36, 0x5c, 0x9b, 0xbb, 0xf1, 0x66, 0xb4, 0xb9,
	0xd3, 0x8a, 0x74, 0x62, 0xa6, 0xfd, 0x3a, 0x54, 0xa9, 0x47, 0x82, 0x18, 0x3b, 0xb0, 0x99, 0x49,
	0x4c, 0x36, 0xd2, 0x53, 0xa8, 0x49, 0x1e, 0x16, 0x2f, 0xcb, 0x12, 0xdb, 0x40, 0x4e, 0xc0, 0x2e,
	0x6c, 0x3c, 0xe3, 0x3b, 0x4e, 0x7c, 0x9b, 0xaf, 0xc2, 0x7c, 0x33, 0x5b, 0xa6, 0xcd, 0x5c, 0xce,
	0x6c, 0x66, 0x73, 0x3d, 0xf1, 0x13, 0x68, 0xa5, 0x21, 0x24, 0xeb, 0x1b, 0xb9, 0x95, 0x5e, 0xac,
	0x33, 0xfe, 0x79, 0xde, 0x7c, 0x69, 0x5e, 0x45, 0x73, 0xae, 0x7e, 0x02, 0xa9, 0xa4, 0xed, 0x34,
	0xe9, 0xa4, 0x6f, 0xd3, 0xa4, 0xf1, 0x73, 0xd8, 0x70, 0xc8, 0x78, 0x72, 0x7a, 0x15, 0x5e, 0x2a,
	0x4c, 0x39, 0x07, 0x93, 0x0e, 0x27, 0x61, 0xba, 0x80, 0xd8, 0x52, 0x53, 0x71, 0x6a, 0x28, 0xab,
	0xc2, 0xef, 0x03, 0x6b, 0x71, 0x1f, 0xe0, 0x5f, 0x2d, 0xd8, 0x48, 0xb9, 0xca, 0xea, 0x66, 0x8f,
	0xe7, 0xeb, 0x50, 0x19, 0x4a, 0xfc, 0xa6, 0xc3, 0x7e, 0x26, 0x37, 0x4e, 0x45, 0x73, 0xe3, 0xd8,
	0xca, 0x8d, 0x73, 0x07, 0xd6, 0x4e, 0x46, 0xb3, 0xe0, 0xdd, 0x60, 0xec, 0x06, 0x74, 0x48, 0xa2,
	0x58, 0xde, 0x47, 0xab, 0xdc, 0xfa, 0x5c, 0x1a, 0xf1, 0x39, 0x6c, 0xca, 0x65, 0xce, 0xb0, 0x96,
	0xc8, 0x56, 0x1e, 0xb9, 0xac, 0x41, 0xae, 0x14, 0x22, 0xdb, 0x3a, 0xe4, 0x2e, 0x6c, 0x65, 0x91,
	0xf5, 0x45, 0xc0, 0x47, 0x49, 0x59, 0xd5, 0x23, 0x47, 0xb9, 0xa7, 0xad, 0xd4, 0x3d, 0x5d, 0xb0,
	0x70, 0xdf, 0x26, 0x55, 0x4f, 0xed, 0xc4, 0x27, 0x60, 0xb3, 0xb9, 0x72, 0x1f, 0x5e, 0x7a, 0xa7,
	0x70, 0x67, 0xfc, 0x5e, 0x1c, 0x85, 0xd4, 0x27, 0xfb, 0x17, 0x6a, 0xe1, 0xb6, 0xa1, 0x3e, 0x26,
	0xb1, 0xab, 0xf0, 0x62, 0xc3, 0x42, 0x5e, 0xe9, 0x46, 0xac, 0x18, 0x36, 0x88, 0xbd, 0xd8, 0x20,
	0xf8, 0x3b, 0x71, 0xa8, 0x28, 0xe0, 0x1f, 0x92, 0xca, 0x39, 0xac, 0x2f, 0x96, 0x62, 0x9e, 0x87,
	0x4a, 0xd7, 0x2a, 0xa0, 0x5b, 0x36, 0xd0, 0x55, 0x65, 0x92, 0x52, 0x13, 0x5b, 0xad, 0x09, 0xfe,
	0x04, 0x90, 0x8a, 0x6c, 0x68, 0x80, 0x73, 0x58, 0x97, 0xdb, 0x5a, 0xe1, 0xf7, 0x1f, 0xd6, 0x5f,
	0xcb, 0x2d, 0x95, 0x8c, 0x9d, 0x39, 0xd0, 0x5a, 0x80, 0x54, 0x64, 0xb9, 0xcf, 0x0f, 0x61, 0x5d,
	0xee, 0xff, 0x0f, 0xe3, 0xc3, 0xc2, 0xab, 0x81, 0x64, 0xf8, 0xb7, 0xd0, 0x16, 0x45, 0xf9, 0x7a,
	0x72, 0x16, 0xf8, 0x13, 0xd7, 0x7b, 0x1d, 0xfa, 0x1f, 0x92, 0xf5, 0x36, 0xd4, 0x67, 0x91, 0xda,
	0x5b, 0x35, 0x36, 0xec, 0x7b, 0x78, 0x1f, 0x76, 0x34, 0x40, 0x72, 0x11, 0xee, 0xc0, 0x9a, 0x27,
	0xcd, 0x83, 0x78, 0xf2, 0x8e, 0x04, 0xf2, 0x2c, 0x58, 0x9d, 0x5b, 0x5f, 0x31, 0x23, 0xfe, 0x81,
	0x6b, 0xa5, 0xef, 0x09, 0xf1, 0x34, 0x6c, 0x97, 0x8b, 0xa1, 0x12, 0x2c, 0xa7, 0x08, 0xbe, 0x84,
	0x8e, 0x2e, 0xb8, 0x64, 0xb8, 0x03, 0x8d, 0x33, 0x42, 0xbc, 0xc1, 0x2c, 0xf4, 0x65, 0xdc, 0x3a,
	0x1b, 0xbf, 0x0e, 0x7d, 0x26, 0x02, 0x58, 0x5d, 0x94, 0x8b, 0x25, 0x19, 0xe3, 0x3f, 0x2c, 0x2e,
	0x06, 0xfb, 0x63, 0xf7, 0x2d, 0x79, 0x35, 0x9a, 0x8d, 0x8f, 0x03, 0x97, 0xfe, 0x2f, 0xf5, 0x65,
	0xe2, 0x6f, 0x44, 0xe8, 0xdb, 0x91, 0x38, 0x01, 0xab, 0x8e, 0x1c, 0xa1, 0x16, 0x54, 0xcf, 0xa8,
	0x17, 0x8b, 0x27, 0x42, 0xd5, 0x11, 0x03, 0xfc, 0x94, 0x57, 0x32, 0x4b, 0x4b, 0xe6, 0xfa, 0x31,
	0x34, 0xe3, 0xb9, 0x91, 0x33, 0xbb, 0xe6, 0x2c, 0x0c, 0xf8, 0x37, 0x0b, 0x5a, 0x6f, 0x5c, 0x9f,
	0xb2, 0x4e, 0xfd, 0x26, 0x88, 0xc3, 0x0b, 0x65, 0x13, 0xcb, 0x74, 0xa2, 0xb6, 0xc5, 0x45, 0x4a,
	0x5d, 0xe4, 0x13, 0xa1, 0x9b, 0x00, 0x49, 0xdf, 0x47, 0xed, 0x32, 0xff, 0xd8, 0x9c, 0x37, 0x7e,
	0x54, 0x20, 0x0d, 0xd2, 0xb7, 0xb3, 0x9d, 0xbe, 0x9d, 0xf1, 0x36, 0x6c, 0x66, 0x98, 0xc8, 0xae,
	0xbe, 0x80, 0xad, 0x43, 0x12, 0x73, 0xdb, 0x0b, 0xee, 0x1c, 0x2d, 0x29, 0x1e, 0x77, 0x32, 0x0f,
	0xb2, 0xa3, 0x92, 0x76, 0x51, 0xd2, 0x24, 0xf7, 0x01, 0x1a, 0x84, 0x61, 0x0d, 0xa8, 0x87, 0xff,
	0xb2, 0x60, 0x3b, 0x87, 0x2d, 0x0b, 0xfb, 0x06, 0xea, 0x82, 0xbb, 0x28, 0xd0, 0xca, 0xde, 0x17,
	0x66, 0x75, 0xaa, 0x0b, 0xd0, 0x8b, 0xe8, 0x78, 0xea, 0x93, 0x81, 0x08, 0xe2, 0xcc, 0x83, 0x75,
	0xbe, 0x84, 0xd5, 0xd4, 0x97, 0x2b, 0x8b, 0xa0, 0xbd, 0xbf, 0xaf, 0xc3, 0xaa, 0xd0, 0xdf, 0x2f,
	0x49, 0x78, 0x4a, 0x4f, 0x08, 0x3a, 0x87, 0xf5, 0xdc, 0xbb, 0x04, 0x3d, 0x32, 0xf3, 0xd5, 0xbe,
	0x77, 0x3a, 0x8f, 0x97, 0x9f, 0x20, 0x97, 0xae, 0x84, 0x4e, 0x00, 0x16, 0x6f, 0x0d, 0xd4, 0x35,
	0x44, 0xc8, 0xbd, 0x68, 0x3a, 0x77, 0x97, 0xf0, 0x4c, 0x40, 0x28, 0x5c, 0x53, 0x5f, 0x1d, 0xe8,
	0x9e, 0x61, 0xb2, 0xe6, 0x7d, 0xd3, 0xb9, 0xbf, 0x94, 0x6f, 0x02, 0xe5, 0xc3, 0x6a, 0x4a, 0x94,
	0xa3, 0xfb, 0x57, 0x78, 0x93, 0x74, 0x1e, 0x2c, 0xe7, 0xac, 0x26, 0xa6, 0x6a, 0x69, 0x63, 0x62,
	0x1a, 0x4d, 0x6f, 0x4c, 0x4c, 0x27, 0xce, 0xd5, 0x1a, 0x5e, 0x02, 0xa5, 0x91, 0xe9, 0x97, 0xd4,
	0x50, 0x07, 0xa5, 0xaa, 0x60, 0x23, 0x94, 0x46, 0x79, 0x1b, 0xa1, 0xb4, 0xb2, 0xba, 0x84, 0x86,
	0xb0, 0xa2, 0xa8, 0x65, 0x74, 0xb7, 0xa0, 0xfe, 0x69, 0x19, 0xdb, 0xb9, 0xb7, 0x8c, 0x6b, 0x82,
	0x33, 0x81, 0xb5, 0xb4, 0x26, 0x45, 0x0f, 0x8a, 0xcb, 0x9f, 0x41, 0x7b, 0xb8, 0xa4, 0xb7, 0x26,
	0x31, 0xde, 0x85, 0x97, 0x24, 0xa6, 0xf6, 0xe0, 0xbd, 0x65, 0x5c, 0xb3, 0xfd, 0x9e, 0xe8, 0xc5,
	0xc2, 0x7e, 0xcf, 0x4a, 0xda, 0xc2, 0x7e, 0xcf, 0x49, 0x50, 0x71, 0x5a, 0x2c, 0x32, 0x36, 0x9e,
	0x16, 0x39, 0xc9, 0x69, 0x3c, 0x2d, 0xf2, 0x12, 0x51, 0x80, 0x2c, 0xa4, 0x99, 0x11, 0x24, 0xa7,
	0x1b, 0x8d, 0x20, 0x1a, 0x9d, 0xc7, 0x41, 0x16, 0x02, 0xcd, 0x08, 0x92, 0x13, 0x83, 0x46, 0x10,
	0x8d, 0xda, 0x2b, 0xa1, 0x44, 0x7e, 0x2b, 0x22, 0xc7, 0x78, 0xac, 0x9b, 0x94, 0xa1, 0xf1, 0x58,
	0x37, 0x2a, 0x3c, 0x5c, 0x42, 0xef, 0xf9, 0xcb, 0x2a, 0xa3, 0xaf, 0x50, 0xc1, 0x05, 0xa1, 0xd7,
	0x79, 0x9d, 0x4f, 0xaf, 0x30, 0x43, 0x4d, 0x3b, 0xa7, 0x77, 0x8a, 0x6e, 0x33, 0xad, 0x60, 0x2b,
	0xba, 0xcd, 0xf4, 0x52, 0x4a, 0xec, 0x86, 0x94, 0x46, 0x31, 0xee, 0x06, 0x9d, 0xa6, 0x32, 0xee,
	0x06, 0xbd, 0xec, 0x29, 0xa1, 0x10, 0x3e, 0xca, 0x68, 0x07, 0xf4, 0x70, 0x59, 0x8d, 0x21, 0x10,
	0x7b, 0x57, 0x93, 0x24, 0xb8, 0x74, 0x5c, 0xe3, 0xff, 0xff, 0x7e, 0xf2, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf7, 0x4f, 0x2a, 0xd2, 0x1c, 0x17, 0x00, 0x00,
}
