// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bottle/bottle.proto

package fullbottle_srv_bottle

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId               int64    `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	FolderId             int64    `protobuf:"varint,6,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{0}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FileInfo) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *FileInfo) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *FileInfo) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *FileInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *FileInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type FolderInfo struct {
	FolderId             int64         `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64         `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreateTime           int64         `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64         `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Folders              []*FolderInfo `protobuf:"bytes,6,rep,name=folders,proto3" json:"folders,omitempty"`
	Files                []*FileInfo   `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FolderInfo) Reset()         { *m = FolderInfo{} }
func (m *FolderInfo) String() string { return proto.CompactTextString(m) }
func (*FolderInfo) ProtoMessage()    {}
func (*FolderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{1}
}

func (m *FolderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FolderInfo.Unmarshal(m, b)
}
func (m *FolderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FolderInfo.Marshal(b, m, deterministic)
}
func (m *FolderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FolderInfo.Merge(m, src)
}
func (m *FolderInfo) XXX_Size() int {
	return xxx_messageInfo_FolderInfo.Size(m)
}
func (m *FolderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FolderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FolderInfo proto.InternalMessageInfo

func (m *FolderInfo) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *FolderInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FolderInfo) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *FolderInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *FolderInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *FolderInfo) GetFolders() []*FolderInfo {
	if m != nil {
		return m.Folders
	}
	return nil
}

func (m *FolderInfo) GetFiles() []*FileInfo {
	if m != nil {
		return m.Files
	}
	return nil
}

type GetBottleMetadataRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBottleMetadataRequest) Reset()         { *m = GetBottleMetadataRequest{} }
func (m *GetBottleMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetBottleMetadataRequest) ProtoMessage()    {}
func (*GetBottleMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{2}
}

func (m *GetBottleMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBottleMetadataRequest.Unmarshal(m, b)
}
func (m *GetBottleMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBottleMetadataRequest.Marshal(b, m, deterministic)
}
func (m *GetBottleMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBottleMetadataRequest.Merge(m, src)
}
func (m *GetBottleMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetBottleMetadataRequest.Size(m)
}
func (m *GetBottleMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBottleMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBottleMetadataRequest proto.InternalMessageInfo

func (m *GetBottleMetadataRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetBottleMetadataResponse struct {
	Bid                  int64    `protobuf:"varint,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Capacity             int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Remain               int64    `protobuf:"varint,3,opt,name=remain,proto3" json:"remain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBottleMetadataResponse) Reset()         { *m = GetBottleMetadataResponse{} }
func (m *GetBottleMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetBottleMetadataResponse) ProtoMessage()    {}
func (*GetBottleMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{3}
}

func (m *GetBottleMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBottleMetadataResponse.Unmarshal(m, b)
}
func (m *GetBottleMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBottleMetadataResponse.Marshal(b, m, deterministic)
}
func (m *GetBottleMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBottleMetadataResponse.Merge(m, src)
}
func (m *GetBottleMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetBottleMetadataResponse.Size(m)
}
func (m *GetBottleMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBottleMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBottleMetadataResponse proto.InternalMessageInfo

func (m *GetBottleMetadataResponse) GetBid() int64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *GetBottleMetadataResponse) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *GetBottleMetadataResponse) GetRemain() int64 {
	if m != nil {
		return m.Remain
	}
	return 0
}

type InitBottleRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Capacity             int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitBottleRequest) Reset()         { *m = InitBottleRequest{} }
func (m *InitBottleRequest) String() string { return proto.CompactTextString(m) }
func (*InitBottleRequest) ProtoMessage()    {}
func (*InitBottleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{4}
}

func (m *InitBottleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBottleRequest.Unmarshal(m, b)
}
func (m *InitBottleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBottleRequest.Marshal(b, m, deterministic)
}
func (m *InitBottleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBottleRequest.Merge(m, src)
}
func (m *InitBottleRequest) XXX_Size() int {
	return xxx_messageInfo_InitBottleRequest.Size(m)
}
func (m *InitBottleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBottleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitBottleRequest proto.InternalMessageInfo

func (m *InitBottleRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *InitBottleRequest) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type InitBottleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitBottleResponse) Reset()         { *m = InitBottleResponse{} }
func (m *InitBottleResponse) String() string { return proto.CompactTextString(m) }
func (*InitBottleResponse) ProtoMessage()    {}
func (*InitBottleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{5}
}

func (m *InitBottleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBottleResponse.Unmarshal(m, b)
}
func (m *InitBottleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBottleResponse.Marshal(b, m, deterministic)
}
func (m *InitBottleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBottleResponse.Merge(m, src)
}
func (m *InitBottleResponse) XXX_Size() int {
	return xxx_messageInfo_InitBottleResponse.Size(m)
}
func (m *InitBottleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBottleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitBottleResponse proto.InternalMessageInfo

type UpdateBottleRequest struct {
	Bid                  int64    `protobuf:"varint,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Capacity             int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBottleRequest) Reset()         { *m = UpdateBottleRequest{} }
func (m *UpdateBottleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBottleRequest) ProtoMessage()    {}
func (*UpdateBottleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{6}
}

func (m *UpdateBottleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBottleRequest.Unmarshal(m, b)
}
func (m *UpdateBottleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBottleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBottleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBottleRequest.Merge(m, src)
}
func (m *UpdateBottleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBottleRequest.Size(m)
}
func (m *UpdateBottleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBottleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBottleRequest proto.InternalMessageInfo

func (m *UpdateBottleRequest) GetBid() int64 {
	if m != nil {
		return m.Bid
	}
	return 0
}

func (m *UpdateBottleRequest) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type UpdateBottleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBottleResponse) Reset()         { *m = UpdateBottleResponse{} }
func (m *UpdateBottleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBottleResponse) ProtoMessage()    {}
func (*UpdateBottleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{7}
}

func (m *UpdateBottleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBottleResponse.Unmarshal(m, b)
}
func (m *UpdateBottleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBottleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBottleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBottleResponse.Merge(m, src)
}
func (m *UpdateBottleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBottleResponse.Size(m)
}
func (m *UpdateBottleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBottleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBottleResponse proto.InternalMessageInfo

type GetFolderInfoRequest struct {
	// Types that are valid to be assigned to Ident:
	//	*GetFolderInfoRequest_FolderId
	//	*GetFolderInfoRequest_Path
	Ident                isGetFolderInfoRequest_Ident `protobuf_oneof:"ident"`
	OwnerId              int64                        `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetFolderInfoRequest) Reset()         { *m = GetFolderInfoRequest{} }
func (m *GetFolderInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetFolderInfoRequest) ProtoMessage()    {}
func (*GetFolderInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{8}
}

func (m *GetFolderInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFolderInfoRequest.Unmarshal(m, b)
}
func (m *GetFolderInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFolderInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetFolderInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFolderInfoRequest.Merge(m, src)
}
func (m *GetFolderInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetFolderInfoRequest.Size(m)
}
func (m *GetFolderInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFolderInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFolderInfoRequest proto.InternalMessageInfo

type isGetFolderInfoRequest_Ident interface {
	isGetFolderInfoRequest_Ident()
}

type GetFolderInfoRequest_FolderId struct {
	FolderId int64 `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3,oneof"`
}

type GetFolderInfoRequest_Path struct {
	Path string `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

func (*GetFolderInfoRequest_FolderId) isGetFolderInfoRequest_Ident() {}

func (*GetFolderInfoRequest_Path) isGetFolderInfoRequest_Ident() {}

func (m *GetFolderInfoRequest) GetIdent() isGetFolderInfoRequest_Ident {
	if m != nil {
		return m.Ident
	}
	return nil
}

func (m *GetFolderInfoRequest) GetFolderId() int64 {
	if x, ok := m.GetIdent().(*GetFolderInfoRequest_FolderId); ok {
		return x.FolderId
	}
	return 0
}

func (m *GetFolderInfoRequest) GetPath() string {
	if x, ok := m.GetIdent().(*GetFolderInfoRequest_Path); ok {
		return x.Path
	}
	return ""
}

func (m *GetFolderInfoRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetFolderInfoRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetFolderInfoRequest_FolderId)(nil),
		(*GetFolderInfoRequest_Path)(nil),
	}
}

type GetFolderInfoResponse struct {
	Folder               *FolderInfo `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetFolderInfoResponse) Reset()         { *m = GetFolderInfoResponse{} }
func (m *GetFolderInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetFolderInfoResponse) ProtoMessage()    {}
func (*GetFolderInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{9}
}

func (m *GetFolderInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFolderInfoResponse.Unmarshal(m, b)
}
func (m *GetFolderInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFolderInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetFolderInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFolderInfoResponse.Merge(m, src)
}
func (m *GetFolderInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetFolderInfoResponse.Size(m)
}
func (m *GetFolderInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFolderInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFolderInfoResponse proto.InternalMessageInfo

func (m *GetFolderInfoResponse) GetFolder() *FolderInfo {
	if m != nil {
		return m.Folder
	}
	return nil
}

type CreateFolderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64    `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFolderRequest) Reset()         { *m = CreateFolderRequest{} }
func (m *CreateFolderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFolderRequest) ProtoMessage()    {}
func (*CreateFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{10}
}

func (m *CreateFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFolderRequest.Unmarshal(m, b)
}
func (m *CreateFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFolderRequest.Marshal(b, m, deterministic)
}
func (m *CreateFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFolderRequest.Merge(m, src)
}
func (m *CreateFolderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFolderRequest.Size(m)
}
func (m *CreateFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFolderRequest proto.InternalMessageInfo

func (m *CreateFolderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFolderRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CreateFolderRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type CreateFolderResponse struct {
	FolderId             int64    `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFolderResponse) Reset()         { *m = CreateFolderResponse{} }
func (m *CreateFolderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFolderResponse) ProtoMessage()    {}
func (*CreateFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{11}
}

func (m *CreateFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFolderResponse.Unmarshal(m, b)
}
func (m *CreateFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFolderResponse.Marshal(b, m, deterministic)
}
func (m *CreateFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFolderResponse.Merge(m, src)
}
func (m *CreateFolderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFolderResponse.Size(m)
}
func (m *CreateFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFolderResponse proto.InternalMessageInfo

func (m *CreateFolderResponse) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

type UpdateFolderRequest struct {
	FolderId             int64    `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId             int64    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFolderRequest) Reset()         { *m = UpdateFolderRequest{} }
func (m *UpdateFolderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFolderRequest) ProtoMessage()    {}
func (*UpdateFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{12}
}

func (m *UpdateFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFolderRequest.Unmarshal(m, b)
}
func (m *UpdateFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFolderRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFolderRequest.Merge(m, src)
}
func (m *UpdateFolderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFolderRequest.Size(m)
}
func (m *UpdateFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFolderRequest proto.InternalMessageInfo

func (m *UpdateFolderRequest) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *UpdateFolderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateFolderRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *UpdateFolderRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type UpdateFolderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFolderResponse) Reset()         { *m = UpdateFolderResponse{} }
func (m *UpdateFolderResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFolderResponse) ProtoMessage()    {}
func (*UpdateFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{13}
}

func (m *UpdateFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFolderResponse.Unmarshal(m, b)
}
func (m *UpdateFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFolderResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFolderResponse.Merge(m, src)
}
func (m *UpdateFolderResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFolderResponse.Size(m)
}
func (m *UpdateFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFolderResponse proto.InternalMessageInfo

type RemoveFolderRequest struct {
	FolderId             int64    `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFolderRequest) Reset()         { *m = RemoveFolderRequest{} }
func (m *RemoveFolderRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFolderRequest) ProtoMessage()    {}
func (*RemoveFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{14}
}

func (m *RemoveFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFolderRequest.Unmarshal(m, b)
}
func (m *RemoveFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFolderRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFolderRequest.Merge(m, src)
}
func (m *RemoveFolderRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFolderRequest.Size(m)
}
func (m *RemoveFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFolderRequest proto.InternalMessageInfo

func (m *RemoveFolderRequest) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

func (m *RemoveFolderRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type RemoveFolderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFolderResponse) Reset()         { *m = RemoveFolderResponse{} }
func (m *RemoveFolderResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFolderResponse) ProtoMessage()    {}
func (*RemoveFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{15}
}

func (m *RemoveFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFolderResponse.Unmarshal(m, b)
}
func (m *RemoveFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFolderResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFolderResponse.Merge(m, src)
}
func (m *RemoveFolderResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFolderResponse.Size(m)
}
func (m *RemoveFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFolderResponse proto.InternalMessageInfo

type GetFileInfoRequest struct {
	FileId               int64    `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileInfoRequest) Reset()         { *m = GetFileInfoRequest{} }
func (m *GetFileInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileInfoRequest) ProtoMessage()    {}
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{16}
}

func (m *GetFileInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileInfoRequest.Unmarshal(m, b)
}
func (m *GetFileInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetFileInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileInfoRequest.Merge(m, src)
}
func (m *GetFileInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileInfoRequest.Size(m)
}
func (m *GetFileInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileInfoRequest proto.InternalMessageInfo

func (m *GetFileInfoRequest) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *GetFileInfoRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type GetFileInfoResponse struct {
	File                 *FileInfo `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetFileInfoResponse) Reset()         { *m = GetFileInfoResponse{} }
func (m *GetFileInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileInfoResponse) ProtoMessage()    {}
func (*GetFileInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{17}
}

func (m *GetFileInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileInfoResponse.Unmarshal(m, b)
}
func (m *GetFileInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetFileInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileInfoResponse.Merge(m, src)
}
func (m *GetFileInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileInfoResponse.Size(m)
}
func (m *GetFileInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileInfoResponse proto.InternalMessageInfo

func (m *GetFileInfoResponse) GetFile() *FileInfo {
	if m != nil {
		return m.File
	}
	return nil
}

type UpdateFileRequest struct {
	FileId  int64 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId int64 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// form
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FolderId             int64    `protobuf:"varint,4,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileRequest) Reset()         { *m = UpdateFileRequest{} }
func (m *UpdateFileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFileRequest) ProtoMessage()    {}
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{18}
}

func (m *UpdateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileRequest.Unmarshal(m, b)
}
func (m *UpdateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileRequest.Merge(m, src)
}
func (m *UpdateFileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFileRequest.Size(m)
}
func (m *UpdateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileRequest proto.InternalMessageInfo

func (m *UpdateFileRequest) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *UpdateFileRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *UpdateFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateFileRequest) GetFolderId() int64 {
	if m != nil {
		return m.FolderId
	}
	return 0
}

type UpdateFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileResponse) Reset()         { *m = UpdateFileResponse{} }
func (m *UpdateFileResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFileResponse) ProtoMessage()    {}
func (*UpdateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{19}
}

func (m *UpdateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileResponse.Unmarshal(m, b)
}
func (m *UpdateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileResponse.Merge(m, src)
}
func (m *UpdateFileResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFileResponse.Size(m)
}
func (m *UpdateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileResponse proto.InternalMessageInfo

type RemoveFileRequest struct {
	FileId               int64    `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFileRequest) Reset()         { *m = RemoveFileRequest{} }
func (m *RemoveFileRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFileRequest) ProtoMessage()    {}
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{20}
}

func (m *RemoveFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFileRequest.Unmarshal(m, b)
}
func (m *RemoveFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFileRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFileRequest.Merge(m, src)
}
func (m *RemoveFileRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFileRequest.Size(m)
}
func (m *RemoveFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFileRequest proto.InternalMessageInfo

func (m *RemoveFileRequest) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *RemoveFileRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type RemoveFileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFileResponse) Reset()         { *m = RemoveFileResponse{} }
func (m *RemoveFileResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFileResponse) ProtoMessage()    {}
func (*RemoveFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f847e5351336bd8, []int{21}
}

func (m *RemoveFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFileResponse.Unmarshal(m, b)
}
func (m *RemoveFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFileResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFileResponse.Merge(m, src)
}
func (m *RemoveFileResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFileResponse.Size(m)
}
func (m *RemoveFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFileResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FileInfo)(nil), "fullbottle.srv.bottle.FileInfo")
	proto.RegisterType((*FolderInfo)(nil), "fullbottle.srv.bottle.FolderInfo")
	proto.RegisterType((*GetBottleMetadataRequest)(nil), "fullbottle.srv.bottle.GetBottleMetadataRequest")
	proto.RegisterType((*GetBottleMetadataResponse)(nil), "fullbottle.srv.bottle.GetBottleMetadataResponse")
	proto.RegisterType((*InitBottleRequest)(nil), "fullbottle.srv.bottle.InitBottleRequest")
	proto.RegisterType((*InitBottleResponse)(nil), "fullbottle.srv.bottle.InitBottleResponse")
	proto.RegisterType((*UpdateBottleRequest)(nil), "fullbottle.srv.bottle.UpdateBottleRequest")
	proto.RegisterType((*UpdateBottleResponse)(nil), "fullbottle.srv.bottle.UpdateBottleResponse")
	proto.RegisterType((*GetFolderInfoRequest)(nil), "fullbottle.srv.bottle.GetFolderInfoRequest")
	proto.RegisterType((*GetFolderInfoResponse)(nil), "fullbottle.srv.bottle.GetFolderInfoResponse")
	proto.RegisterType((*CreateFolderRequest)(nil), "fullbottle.srv.bottle.CreateFolderRequest")
	proto.RegisterType((*CreateFolderResponse)(nil), "fullbottle.srv.bottle.CreateFolderResponse")
	proto.RegisterType((*UpdateFolderRequest)(nil), "fullbottle.srv.bottle.UpdateFolderRequest")
	proto.RegisterType((*UpdateFolderResponse)(nil), "fullbottle.srv.bottle.UpdateFolderResponse")
	proto.RegisterType((*RemoveFolderRequest)(nil), "fullbottle.srv.bottle.RemoveFolderRequest")
	proto.RegisterType((*RemoveFolderResponse)(nil), "fullbottle.srv.bottle.RemoveFolderResponse")
	proto.RegisterType((*GetFileInfoRequest)(nil), "fullbottle.srv.bottle.GetFileInfoRequest")
	proto.RegisterType((*GetFileInfoResponse)(nil), "fullbottle.srv.bottle.GetFileInfoResponse")
	proto.RegisterType((*UpdateFileRequest)(nil), "fullbottle.srv.bottle.UpdateFileRequest")
	proto.RegisterType((*UpdateFileResponse)(nil), "fullbottle.srv.bottle.UpdateFileResponse")
	proto.RegisterType((*RemoveFileRequest)(nil), "fullbottle.srv.bottle.RemoveFileRequest")
	proto.RegisterType((*RemoveFileResponse)(nil), "fullbottle.srv.bottle.RemoveFileResponse")
}

func init() { proto.RegisterFile("proto/bottle/bottle.proto", fileDescriptor_3f847e5351336bd8) }

var fileDescriptor_3f847e5351336bd8 = []byte{
	// 790 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0xf5, 0xfb, 0x31, 0xb9, 0xb9, 0xb8, 0xa6, 0x9d, 0x5c, 0xc5, 0x41, 0x91, 0x94, 0x2b, 0xe7,
	0x01, 0xa7, 0x48, 0xd0, 0x45, 0xd1, 0x55, 0x13, 0x20, 0x89, 0x0b, 0x64, 0xa3, 0xb6, 0xeb, 0x40,
	0xb6, 0x68, 0x84, 0x80, 0x2c, 0xb9, 0x12, 0x9d, 0xa6, 0x5d, 0xf4, 0x1b, 0xfa, 0x3d, 0xfd, 0xa3,
	0xfe, 0x45, 0xc1, 0x87, 0x6d, 0xd2, 0x12, 0x6d, 0xf5, 0xb1, 0x8a, 0x38, 0x9c, 0x99, 0x73, 0x66,
	0x38, 0x73, 0x62, 0xd8, 0x9b, 0xc6, 0x11, 0x8b, 0xce, 0x86, 0x11, 0x63, 0x01, 0x51, 0x7f, 0xfa,
	0xc2, 0x86, 0x76, 0xc6, 0xb3, 0x20, 0x50, 0x96, 0x24, 0x7e, 0xec, 0xcb, 0x4f, 0xfc, 0xa3, 0x08,
	0x8d, 0x6b, 0x1a, 0x90, 0x41, 0x38, 0x8e, 0xd0, 0xbf, 0x50, 0xa2, 0xbe, 0x53, 0x3c, 0x2c, 0xf6,
	0xca, 0x6e, 0x89, 0xfa, 0xe8, 0x7f, 0xa8, 0x8f, 0x69, 0x40, 0xee, 0xa9, 0xef, 0x94, 0x84, 0xb1,
	0xc6, 0x8f, 0x03, 0x1f, 0x21, 0xa8, 0x84, 0xde, 0x84, 0x38, 0xe5, 0xc3, 0x62, 0xaf, 0xe9, 0x8a,
	0x6f, 0x6e, 0x4b, 0xe8, 0x17, 0xe2, 0x54, 0x84, 0xa7, 0xf8, 0xe6, 0xb6, 0x07, 0x2f, 0x79, 0x70,
	0xaa, 0xd2, 0x8f, 0x7f, 0xa3, 0x7d, 0x68, 0x8e, 0xa3, 0xc0, 0x27, 0x31, 0x4f, 0x5b, 0x13, 0xce,
	0x0d, 0x69, 0x18, 0xf8, 0x68, 0x0f, 0x1a, 0xd1, 0xa7, 0x50, 0xde, 0xd5, 0xc5, 0x5d, 0x5d, 0x9c,
	0x07, 0x3e, 0x3a, 0x80, 0xad, 0x51, 0x4c, 0x3c, 0x46, 0xee, 0x19, 0x9d, 0x10, 0xa7, 0x21, 0x6e,
	0x41, 0x9a, 0xde, 0xd3, 0x09, 0xe1, 0x0e, 0xb3, 0xa9, 0xbf, 0x70, 0x68, 0x4a, 0x07, 0x69, 0xe2,
	0x0e, 0xf8, 0x5b, 0x09, 0xe0, 0x5a, 0x22, 0xf1, 0x6a, 0x0d, 0x22, 0xc5, 0x15, 0x22, 0xf3, 0x0a,
	0x4b, 0x5a, 0x85, 0xfb, 0xd0, 0x9c, 0x7a, 0x31, 0x09, 0x19, 0x0f, 0x28, 0xcb, 0x00, 0x69, 0x48,
	0xd3, 0xab, 0x6c, 0xa2, 0x57, 0x5d, 0xa5, 0x87, 0x5e, 0x43, 0x5d, 0xc2, 0x27, 0x4e, 0xed, 0xb0,
	0xdc, 0xdb, 0x3a, 0x7f, 0xde, 0xcf, 0x7c, 0xb3, 0xfe, 0xb2, 0x06, 0x77, 0x1e, 0x81, 0x5e, 0x42,
	0x95, 0xbf, 0x4d, 0xe2, 0xd4, 0x45, 0xe8, 0x81, 0x2d, 0x54, 0x3d, 0xb5, 0x2b, 0xbd, 0xf1, 0x29,
	0x38, 0x37, 0x84, 0x5d, 0x8a, 0xcb, 0x3b, 0xc2, 0x3c, 0xdf, 0x63, 0x9e, 0x4b, 0x3e, 0xce, 0x48,
	0xc2, 0xd0, 0x7f, 0x50, 0x9e, 0x2d, 0x3a, 0xc3, 0x3f, 0xb1, 0x07, 0x7b, 0x19, 0xde, 0xc9, 0x34,
	0x0a, 0x13, 0xc2, 0xdd, 0x87, 0x4b, 0xf7, 0x21, 0xf5, 0x51, 0x17, 0x1a, 0x23, 0x6f, 0xea, 0x8d,
	0x28, 0xfb, 0xac, 0xe6, 0x67, 0x71, 0x46, 0xbb, 0x50, 0x8b, 0xc9, 0xc4, 0xa3, 0xa1, 0x6a, 0xa4,
	0x3a, 0xe1, 0x37, 0xd0, 0x1a, 0x84, 0x54, 0x61, 0x58, 0x99, 0xac, 0x4b, 0x8d, 0x3b, 0x80, 0xf4,
	0x14, 0x92, 0x1e, 0xbe, 0x82, 0xf6, 0x07, 0xd1, 0xeb, 0x54, 0xea, 0xfc, 0xac, 0xf1, 0x2e, 0x74,
	0xcc, 0x24, 0x2a, 0x79, 0x04, 0x9d, 0x1b, 0xc2, 0xb4, 0x77, 0x51, 0xd9, 0x9f, 0xa5, 0x46, 0xec,
	0xb6, 0xa0, 0x0d, 0x59, 0x07, 0x2a, 0x53, 0x8f, 0x3d, 0xc8, 0x21, 0xbb, 0x2d, 0xb8, 0xe2, 0x64,
	0xec, 0x40, 0xd9, 0xd8, 0x81, 0xcb, 0x3a, 0x54, 0xa9, 0x4f, 0x42, 0x86, 0x5d, 0xd8, 0x59, 0x01,
	0x54, 0xaf, 0xf0, 0x0a, 0x6a, 0x32, 0xbd, 0x80, 0xcb, 0x35, 0x43, 0x2a, 0x00, 0x7b, 0xd0, 0xbe,
	0x12, 0xe3, 0x2a, 0xef, 0xe6, 0x35, 0xcc, 0x37, 0xa1, 0x68, 0xdb, 0x84, 0xd2, 0xca, 0x26, 0xd8,
	0xf9, 0xe3, 0x0b, 0xe8, 0x98, 0x10, 0x8a, 0xf5, 0xba, 0x55, 0xc4, 0x5f, 0xe7, 0x2f, 0x67, 0xf2,
	0xfa, 0xbb, 0xeb, 0xab, 0x93, 0xae, 0x98, 0xa4, 0x17, 0x8f, 0x6e, 0x92, 0xc6, 0x77, 0xd0, 0x76,
	0xc9, 0x24, 0x7a, 0xfc, 0x15, 0x5e, 0x3a, 0x4c, 0x29, 0x05, 0x63, 0xa6, 0x53, 0x30, 0xb7, 0x80,
	0xf8, 0x53, 0xcf, 0x17, 0x57, 0xa1, 0x68, 0xd2, 0x5c, 0x34, 0xa4, 0x79, 0x0d, 0xc2, 0x5b, 0x68,
	0x1b, 0x99, 0x54, 0xf3, 0x2f, 0xa0, 0xc2, 0x63, 0xd5, 0xc0, 0x6c, 0x54, 0x0e, 0xe1, 0x8c, 0x9f,
	0xa0, 0xa5, 0x9a, 0x42, 0x97, 0xcb, 0xf4, 0x1b, 0xa4, 0x32, 0xff, 0x95, 0x18, 0x2d, 0xac, 0xac,
	0x8c, 0x43, 0x07, 0x90, 0x8e, 0xac, 0xba, 0x74, 0x03, 0x2d, 0xd5, 0xbd, 0x3f, 0xe3, 0xc3, 0xd3,
	0xeb, 0x89, 0x64, 0xfa, 0xf3, 0xef, 0x0d, 0xd8, 0x96, 0x3b, 0xff, 0x8e, 0xc4, 0x8f, 0x74, 0x44,
	0xd0, 0x13, 0xb4, 0x52, 0x5a, 0x88, 0xce, 0x2c, 0xcd, 0xb3, 0x69, 0x6c, 0xf7, 0x45, 0xfe, 0x00,
	0x55, 0x68, 0x01, 0x8d, 0x00, 0x96, 0xfa, 0x86, 0x7a, 0x96, 0x0c, 0x29, 0x15, 0xed, 0x1e, 0xe5,
	0xf0, 0x5c, 0x80, 0x50, 0xf8, 0x47, 0x57, 0x3a, 0x74, 0x6c, 0x09, 0xce, 0xd0, 0xd4, 0xee, 0x49,
	0x2e, 0xdf, 0x05, 0x54, 0x00, 0xdb, 0x86, 0x96, 0xa1, 0x13, 0x7b, 0x53, 0x52, 0x12, 0xdb, 0x3d,
	0xcd, 0xe7, 0xac, 0x17, 0xa6, 0x4b, 0x90, 0xb5, 0xb0, 0x0c, 0x29, 0xb4, 0x16, 0x96, 0xa5, 0x69,
	0x7a, 0x0f, 0x37, 0x40, 0x65, 0xa8, 0xdb, 0x86, 0x1e, 0x66, 0x41, 0xe9, 0xe2, 0x61, 0x85, 0xca,
	0x10, 0x2c, 0x2b, 0x54, 0xa6, 0x1a, 0x15, 0xd0, 0x18, 0xb6, 0x34, 0x15, 0x41, 0x47, 0x6b, 0xfa,
	0x6f, 0x6a, 0x56, 0xf7, 0x38, 0x8f, 0xab, 0x3e, 0xe6, 0xcb, 0x3d, 0xb7, 0x8e, 0x79, 0x4a, 0x84,
	0xac, 0x63, 0x9e, 0x21, 0x1a, 0x02, 0x64, 0xb9, 0xed, 0x56, 0x90, 0x94, 0xb2, 0x58, 0x41, 0xd2,
	0xd2, 0x81, 0x0b, 0xc3, 0x9a, 0xf8, 0x05, 0x7e, 0xf1, 0x33, 0x00, 0x00, 0xff, 0xff, 0x53, 0xed,
	0xe1, 0xc6, 0x9e, 0x0b, 0x00, 0x00,
}
